//! W6 acceptance (SPEC §3-C): the produced module exposes ONLY the intended exports,
//! and no_std + strip keeps the artifact small. These are analysis-cost **proxies**
//! (D05) — measured and reported, never framed as "reversing difficulty".
#![cfg(windows)]

use ml_oracle::pe;
use mlc::{codegen::build_cdylib, compile_to_rust};

fn contains(haystack: &[u8], needle: &[u8]) -> bool {
    needle.len() <= haystack.len() && haystack.windows(needle.len()).any(|w| w == needle)
}

#[test]
fn produced_module_exports_only_intended_symbols_and_is_stripped() {
    let src = include_str!("../../../examples/discount.mls");
    let rust = compile_to_rust(src).expect("compile");
    let workdir = std::env::temp_dir().join("mlc_w6");
    let dll = build_cdylib(&rust, "discount_w6", &workdir).expect("build");

    // Export table = exactly the reserved version symbol + the mlx_ function (D18).
    let mut exports = pe::read_exports(&dll).expect("read exports");
    exports.sort();
    assert_eq!(
        exports,
        vec![
            "ml_module_abi_version".to_string(),
            "mlx_discount".to_string(),
        ],
        "module must export only ml_module_abi_version + mlx_discount"
    );

    // Analysis-cost proxies (measured/reported, not a reversing-difficulty claim).
    let bytes = std::fs::read(&dll).unwrap();
    let size = bytes.len();
    assert!(
        !contains(&bytes, b"Generated by mlc"),
        "source comment leaked into the stripped binary"
    );
    assert!(
        !contains(&bytes, b"discount.mls"),
        "source filename leaked into the binary"
    );
    // no_std + strip should keep this far under the ~107 KB std build.
    assert!(
        size < 60_000,
        "expected a small stripped no_std dll, got {size} bytes"
    );

    println!("W6 measured: size={size} bytes, exports={exports:?}");
}
