//! W6 acceptance (SPEC §3-C): the produced module exposes ONLY the intended exports,
//! and no_std + strip keeps the artifact small. These are analysis-cost **proxies**
//! (D05) — measured and reported, never framed as "reversing difficulty".
#![cfg(windows)]

use ml_oracle::pe;
use mlc::{codegen::build_cdylib, compile_to_rust};

/// Measured sizes of the stripped `no_std` `discount` module, in bytes.
///
/// **This number is machine-dependent, and that was measured, not assumed.** D3 was decided
/// as "assert the exact value", on the reasoning that `rust-toolchain.toml` pins the
/// toolchain. CI disproved it in one run: the same commit and the same pinned rustc 1.97.1
/// produced 9,728 B on the development machine and 9,216 B on GitHub's `windows-latest`.
/// The pin covers rustc; it does not cover MSVC `link.exe` or the Windows SDK, and the
/// difference is exactly one 512-byte `FileAlignment` block.
///
/// So ten documents were publishing a *this-machine* number as a project fact. The bound
/// below is what can honestly be asserted anywhere, and it is still tight enough to catch
/// the failure that mattered: under the old `size < 60_000` the module could sextuple in
/// silence. `doc_claims.rs` reads these constants out of this file and requires the
/// documents to carry BOTH observations, so the prose cannot go back to implying one exact
/// byte count is universal.
const DISCOUNT_DLL_MEASURED_DEV: u64 = 9_728;
const DISCOUNT_DLL_MEASURED_CI: u64 = 9_216;
const DISCOUNT_DLL_MIN: u64 = 8_192;
const DISCOUNT_DLL_MAX: u64 = 12_288;

fn contains(haystack: &[u8], needle: &[u8]) -> bool {
    needle.len() <= haystack.len() && haystack.windows(needle.len()).any(|w| w == needle)
}

#[test]
fn produced_module_exports_only_intended_symbols_and_is_stripped() {
    let src = include_str!("../../../examples/discount.mls");
    let rust = compile_to_rust(src).expect("compile");
    // Isolate the build tree per test process (build_cdylib expects a unique workdir).
    let workdir = std::env::temp_dir().join(format!("mlc_w6_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&workdir);
    let dll = build_cdylib(&rust, "discount_w6", &workdir)
        .expect("build")
        .dll;

    // Export table = exactly the two reserved symbols + the mlx_ function (D18).
    // `ml_iface_hash` joined `ml_module_abi_version` with the interface-fingerprint slice;
    // the proxy this test reports therefore moved from 2 exports to 3, and SECURITY.md
    // section on P0 measurements was updated in the same PR rather than left stale.
    let mut exports = pe::read_exports(&dll).expect("read exports");
    exports.sort();
    assert_eq!(
        exports,
        vec![
            "ml_iface_hash".to_string(),
            "ml_module_abi_version".to_string(),
            "mlx_discount".to_string(),
        ],
        "module must export only ml_iface_hash + ml_module_abi_version + mlx_discount"
    );

    // Analysis-cost proxies (measured/reported, not a reversing-difficulty claim).
    let bytes = std::fs::read(&dll).unwrap();
    let size = bytes.len();
    assert!(
        !contains(&bytes, b"Generated by mlc"),
        "source comment leaked into the stripped binary"
    );
    assert!(
        !contains(&bytes, b"discount.mls"),
        "source filename leaked into the binary"
    );
    // no_std + strip should keep this far under the ~107 KB std build.
    assert!(
        size < 60_000,
        "expected a small stripped no_std dll, got {size} bytes"
    );
    // ...and "far under" was the whole guard: at `< 60_000` the module could sextuple in
    // silence while ten documents kept publishing an exact byte count (`STATUS.md` D3).
    //
    // The bound is a range because the exact value is not portable — see the constants
    // above, where CI measured 9,216 B against this machine's 9,728 B on the same pinned
    // toolchain. The width is four `FileAlignment` blocks either side of what has actually
    // been observed, which still fails long before a module doubles.
    let size = size as u64;
    assert!(
        (DISCOUNT_DLL_MIN..=DISCOUNT_DLL_MAX).contains(&size),
        "the stripped module is {size} B, outside the asserted \
         {DISCOUNT_DLL_MIN}..={DISCOUNT_DLL_MAX} B. Observed values are \
         {DISCOUNT_DLL_MEASURED_DEV} B (dev machine) and {DISCOUNT_DLL_MEASURED_CI} B \
         (GitHub windows-latest). If this is a deliberate toolchain change, re-measure and \
         update these constants AND the documents doc_claims.rs checks"
    );

    println!("W6 measured: size={size} bytes, exports={exports:?}");

    // Nothing holds the file open here (we read bytes, not LoadLibrary) — clean up.
    let _ = std::fs::remove_dir_all(&workdir);
}
