//! W6 acceptance (SPEC §3-C): the produced module exposes ONLY the intended exports,
//! and no_std + strip keeps the artifact small. These are analysis-cost **proxies**
//! (D05) — measured and reported, never framed as "reversing difficulty".
#![cfg(windows)]

use ml_oracle::pe;
use mlc::{codegen::build_cdylib, compile_to_rust};

/// Measured sizes of the stripped `no_std` `discount` module, in bytes.
///
/// **This number is machine-dependent, and that was measured, not assumed.** D3 was decided
/// as "assert the exact value", on the reasoning that `rust-toolchain.toml` pins the
/// toolchain. CI disproved it in one run: the same commit and the same pinned rustc 1.97.1
/// produced 9,728 B on the development machine and 9,216 B on GitHub's `windows-latest`.
/// The pin covers rustc; it does not cover MSVC `link.exe` or the Windows SDK, and the
/// difference is exactly one 512-byte `FileAlignment` block.
///
/// So ten documents were publishing a *this-machine* number as a project fact. The bound
/// below is what can honestly be asserted anywhere, and it is still tight enough to catch
/// the failure that mattered: under the old `size < 60_000` the module could sextuple in
/// silence. `doc_claims.rs` reads these constants out of this file and requires the
/// documents to carry BOTH observations, so the prose cannot go back to implying one exact
/// byte count is universal.
///
/// **Each constant is asserted against the artifact in the environment it names, not merely
/// reported** (STATUS §9-A A3). For a slice they were used only in a failure message and in
/// the document cross-check, so a toolchain producing a size anywhere inside the range below
/// passed while both numbers — and the four documents that publish them — became quietly
/// false. The word for the two of them is *observations*, and an observation nobody
/// re-observes is prose.
///
/// The pin is per environment rather than "the size is one of these two". Set membership
/// reads as the stronger guard and is the weaker one: a single run sees a single machine, so
/// it can only ever reproduce one of the two, and membership lets the OTHER number rot
/// undetected — which is the failure this row is about. `GITHUB_ACTIONS` separates them.
/// An environment that produces neither fails on purpose: the documents are then publishing
/// a byte count nothing on this machine produces, and the fix is to re-measure both.
const DISCOUNT_DLL_MEASURED_DEV: u64 = 9_728;
const DISCOUNT_DLL_MEASURED_CI: u64 = 9_216;
const DISCOUNT_DLL_MIN: u64 = 8_192;
const DISCOUNT_DLL_MAX: u64 = 12_288;

fn contains(haystack: &[u8], needle: &[u8]) -> bool {
    needle.len() <= haystack.len() && haystack.windows(needle.len()).any(|w| w == needle)
}

#[test]
fn produced_module_exports_only_intended_symbols_and_is_stripped() {
    let src = include_str!("../../../examples/discount.mls");
    let rust = compile_to_rust(src).expect("compile");
    // Isolate the build tree per test process (build_cdylib expects a unique workdir).
    let workdir = std::env::temp_dir().join(format!("mlc_w6_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&workdir);
    let dll = build_cdylib(&rust, "discount_w6", &workdir)
        .expect("build")
        .dll;

    // Export table = exactly the two reserved symbols + the mlx_ function (D18).
    // `ml_iface_hash` joined `ml_module_abi_version` with the interface-fingerprint slice;
    // the proxy this test reports therefore moved from 2 exports to 3, and SECURITY.md
    // section on P0 measurements was updated in the same PR rather than left stale.
    let mut exports = pe::read_exports(&dll).expect("read exports");
    exports.sort();
    assert_eq!(
        exports,
        vec![
            "ml_iface_hash".to_string(),
            "ml_module_abi_version".to_string(),
            "mlx_discount".to_string(),
        ],
        "module must export only ml_iface_hash + ml_module_abi_version + mlx_discount"
    );

    // Analysis-cost proxies (measured/reported, not a reversing-difficulty claim).
    let bytes = std::fs::read(&dll).unwrap();
    let size = bytes.len();
    assert!(
        !contains(&bytes, b"Generated by mlc"),
        "source comment leaked into the stripped binary"
    );
    assert!(
        !contains(&bytes, b"discount.mls"),
        "source filename leaked into the binary"
    );
    // no_std + strip should keep this far under the ~107 KB std build.
    assert!(
        size < 60_000,
        "expected a small stripped no_std dll, got {size} bytes"
    );
    // ...and "far under" was the whole guard: at `< 60_000` the module could sextuple in
    // silence while ten documents kept publishing an exact byte count (`STATUS.md` D3).
    //
    // The bound is a range because the exact value is not portable — see the constants
    // above, where CI measured 9,216 B against this machine's 9,728 B on the same pinned
    // toolchain. The width is two `FileAlignment` blocks below the smaller observation and
    // five above the larger — not symmetric, and the earlier comment here said "four either
    // side", which was simply wrong arithmetic (an audit caught it). What the bound is for
    // is unchanged: it still fails long before a module doubles.
    let size = size as u64;
    assert!(
        (DISCOUNT_DLL_MIN..=DISCOUNT_DLL_MAX).contains(&size),
        "the stripped module is {size} B, outside the asserted \
         {DISCOUNT_DLL_MIN}..={DISCOUNT_DLL_MAX} B. Observed values are \
         {DISCOUNT_DLL_MEASURED_DEV} B (dev machine) and {DISCOUNT_DLL_MEASURED_CI} B \
         (GitHub windows-latest). If this is a deliberate toolchain change, re-measure and \
         update these constants AND the documents doc_claims.rs checks"
    );

    // ...and the range on its own is still not enough, because the two constants above are
    // published as *measurements* in SECURITY.md, STATUS.md and both READMEs. The range
    // admits 10,240 B, and at 10,240 B every one of those documents states a number nothing
    // produces.
    //
    // Pinned PER ENVIRONMENT, not as set membership. Membership would be the wrong
    // invariant: one run sees one machine, so it can reproduce at most one of the two
    // observations, and the other could quietly stop being true forever while this stayed
    // green. Each document sentence names the environment it was measured in, and
    // `GITHUB_ACTIONS` is what tells the two apart.
    let on_ci = std::env::var_os("GITHUB_ACTIONS").is_some();
    let (expected, environment) = if on_ci {
        (DISCOUNT_DLL_MEASURED_CI, "GitHub's windows-latest runner")
    } else {
        (DISCOUNT_DLL_MEASURED_DEV, "the development machine")
    };
    assert_eq!(
        size, expected,
        "the stripped module measures {size} B on {environment}, where SECURITY.md, \
         STATUS.md and both READMEs publish {expected} B. That is not necessarily a defect \
         in the module — the byte count is machine-dependent (D3: the toolchain pin covers \
         rustc, not MSVC link.exe or the Windows SDK) — but it does mean those documents \
         now state a number this environment does not produce. Re-measure and update the \
         constant above AND the documents doc_claims.rs checks, in the same commit"
    );

    println!("W6 measured: size={size} bytes on {environment}, exports={exports:?}");

    // Nothing holds the file open here (we read bytes, not LoadLibrary) — clean up.
    let _ = std::fs::remove_dir_all(&workdir);
}
