//! W4 codegen: typed IR → Rust source (`extern "C"` cdylib), then build to a DLL.
//!
//! Per D19 this is the **provisional rustc lowering**: emit Rust, `cargo build
//! --crate-type cdylib`. The IR is backend-independent, so a C-emit backend can be
//! added later without touching the front/middle end.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::ir::*;

#[derive(Debug, PartialEq, Eq, Clone)]
pub struct CodegenError {
    pub message: String,
}

impl CodegenError {
    pub fn new(message: impl Into<String>) -> Self {
        CodegenError {
            message: message.into(),
        }
    }
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "codegen error: {}", self.message)
    }
}

impl std::error::Error for CodegenError {}

/// Emit Rust source implementing the IR module as a C-ABI cdylib (D18 exports:
/// `mlx_<fn>` + reserved `ml_module_abi_version`).
pub fn emit(module: &IrModule) -> Result<String, CodegenError> {
    let mut out = String::new();
    out.push_str("// Generated by mlc. Do not edit.\n");
    out.push_str("#![no_std]\n");
    out.push_str("#![allow(unused_parens)]\n");
    // A surface `let mut` that is never reassigned is legal Mathless; don't make rustc
    // complain about the faithful lowering.
    out.push_str("#![allow(unused_mut)]\n\n");
    out.push_str("#[no_mangle]\n");
    // Interpolate the single-source ABI version (D18) so the emitted module can't drift.
    let _ = writeln!(
        out,
        "pub extern \"C\" fn ml_module_abi_version() -> u32 {{ {} }}\n",
        crate::abi::ML_MODULE_ABI_VERSION
    );

    for f in &module.functions {
        emit_function(f, &mut out)?;
        out.push('\n');
    }

    // A no_std cdylib requires a panic handler; our arithmetic never panics (panic=abort).
    out.push_str("#[panic_handler]\nfn ml_panic(_: &core::panic::PanicInfo) -> ! { loop {} }\n");
    Ok(out)
}

fn emit_function(f: &IrFunction, out: &mut String) -> Result<(), CodegenError> {
    if !block_always_returns(&f.body) {
        // Backend safety net: typeck rejects this for real source (see `typeck::check`), but
        // directly-built IR could still fall off the end without returning a typed value.
        return Err(CodegenError::new(format!(
            "function '{}' may not return on all paths",
            f.name
        )));
    }

    let mut params: Vec<String> = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, rust_type(p.ty)))
        .collect();

    // `write!` into a String is infallible; the `_ =` documents that.
    out.push_str("#[no_mangle]\n");
    if f.fallible {
        // D17: a fallible fn returns an `i32` status and delivers its value through a
        // `*mut T` out-param appended after the declared parameters.
        params.push(format!("out_value: *mut {}", rust_type(f.ret)));
        let _ = writeln!(
            out,
            "pub extern \"C\" fn mlx_{}({}) -> i32 {{",
            f.name,
            params.join(", ")
        );
    } else {
        let _ = writeln!(
            out,
            "pub extern \"C\" fn mlx_{}({}) -> {} {{",
            f.name,
            params.join(", "),
            rust_type(f.ret)
        );
    }
    for s in &f.body {
        emit_stmt(s, 1, f.fallible, out);
    }
    out.push_str("}\n");
    Ok(())
}

fn rust_type(t: IrType) -> &'static str {
    match t {
        IrType::F64 => "f64",
        IrType::Bool => "bool",
        IrType::I32 => "i32",
    }
}

fn emit_stmt(s: &IrStmt, indent: usize, fallible: bool, out: &mut String) {
    let pad = "    ".repeat(indent);
    match s {
        IrStmt::Return(e) => {
            if fallible {
                // Success: write the value through the out-param, return status 0 (D17).
                let _ = writeln!(
                    out,
                    "{pad}unsafe {{ *out_value = {}; }} return 0;",
                    emit_expr(e)
                );
            } else {
                let _ = writeln!(out, "{pad}return {};", emit_expr(e));
            }
        }
        IrStmt::Fail(code) => {
            // Failure: return the positive domain code; the out-param is left untouched.
            let _ = writeln!(out, "{pad}return {code};");
        }
        IrStmt::Let {
            name,
            value,
            mutable,
        } => {
            // Internal binding — a plain Rust `let`, never an export.
            let kw = if *mutable { "let mut" } else { "let" };
            let _ = writeln!(out, "{pad}{kw} {name} = {};", emit_expr(value));
        }
        IrStmt::Assign { name, value } => {
            // Reassign an in-scope `let mut`. Inside an `if` this mutates the OUTER binding,
            // which is the point of the slice: `if` is a statement, so a mutable local is how
            // a branch result is collected.
            let _ = writeln!(out, "{pad}{name} = {};", emit_expr(value));
        }
        IrStmt::If { cond, body } => {
            let _ = writeln!(out, "{pad}if {} {{", emit_expr(cond));
            for st in body {
                emit_stmt(st, indent + 1, fallible, out);
            }
            let _ = writeln!(out, "{pad}}}");
        }
        IrStmt::While { cond, body } => {
            // A module export may now fail to return (SPEC-while §5.1). There is nothing to
            // emit for that: no fuel counter without the VM R01 rejected, no timeout without a
            // runtime. The contract is documented in HOST_ABI instead.
            let _ = writeln!(out, "{pad}while {} {{", emit_expr(cond));
            for st in body {
                emit_stmt(st, indent + 1, fallible, out);
            }
            let _ = writeln!(out, "{pad}}}");
        }
    }
}

fn emit_expr(e: &IrExpr) -> String {
    match &e.kind {
        IrExprKind::ConstF64(n) => format!("{n:?}f64"),
        IrExprKind::ConstI32(n) => format!("{n}i32"),
        IrExprKind::ConstBool(b) => b.to_string(),
        IrExprKind::Var(name) => name.clone(),
        IrExprKind::Binary { op, lhs, rhs } => {
            format!("({} {} {})", emit_expr(lhs), op_str(*op), emit_expr(rhs))
        }
    }
}

fn op_str(op: IrBinOp) -> &'static str {
    match op {
        IrBinOp::Add => "+",
        IrBinOp::Sub => "-",
        IrBinOp::Mul => "*",
        IrBinOp::Div => "/",
        IrBinOp::Lt => "<",
        IrBinOp::Gt => ">",
        IrBinOp::Le => "<=",
        IrBinOp::Ge => ">=",
        IrBinOp::Eq => "==",
        IrBinOp::Ne => "!=",
    }
}

/// Write `rust_src` as a `cdylib` crate under `workdir/<crate_name>` and build it,
/// returning the produced DLL path. Requires `cargo` on PATH (D19/D20). Windows target
/// (D22): the artifact is `<crate_name>.dll`.
///
/// This is a caller-supplied-dir primitive: the caller must pass a **unique** `workdir` per
/// concurrent invocation (`emit_artifacts` uses a private temp tree; the oracle tests
/// namespace theirs per process). Two calls sharing a `workdir` would race.
pub fn build_cdylib(
    rust_src: &str,
    crate_name: &str,
    workdir: &Path,
) -> Result<PathBuf, CodegenError> {
    let crate_dir = workdir.join(crate_name);
    std::fs::create_dir_all(crate_dir.join("src"))
        .map_err(|e| CodegenError::new(format!("create crate dir: {e}")))?;
    std::fs::write(
        crate_dir.join("Cargo.toml"),
        format!(
            "[package]\nname = \"{crate_name}\"\nversion = \"0.0.0\"\nedition = \"2021\"\npublish = false\n\n[lib]\ncrate-type = [\"cdylib\"]\n\n[profile.release]\npanic = \"abort\"\nstrip = true\nlto = true\nopt-level = \"z\"\n"
        ),
    )
    .map_err(|e| CodegenError::new(format!("write Cargo.toml: {e}")))?;
    std::fs::write(crate_dir.join("src").join("lib.rs"), rust_src)
        .map_err(|e| CodegenError::new(format!("write lib.rs: {e}")))?;

    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".into());
    let status = Command::new(cargo)
        .args(["build", "--release", "--manifest-path"])
        .arg(crate_dir.join("Cargo.toml"))
        .status()
        .map_err(|e| CodegenError::new(format!("spawn cargo: {e}")))?;
    if !status.success() {
        return Err(CodegenError::new("cargo build of generated crate failed"));
    }

    let dll = crate_dir
        .join("target")
        .join("release")
        .join(format!("{crate_name}.dll"));
    if !dll.exists() {
        return Err(CodegenError::new(format!(
            "expected dll not found: {}",
            dll.display()
        )));
    }
    Ok(dll)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compile_to_ir;

    #[test]
    fn emit_discount_produces_extern_c_rust() {
        let ir = compile_to_ir(include_str!("../../examples/discount.mls")).unwrap();
        let rust = emit(&ir).expect("emit");
        assert!(
            rust.contains(r#"pub extern "C" fn mlx_discount(price: f64, vip: bool) -> f64"#),
            "{rust}"
        );
        assert!(rust.contains("#![no_std]"), "{rust}");
        assert!(rust.contains("ml_module_abi_version"), "{rust}");
        assert!(rust.contains("if vip"), "{rust}");
        assert!(rust.contains("return price"), "{rust}");
    }

    #[test]
    fn rejects_function_without_guaranteed_return() {
        // Only statement is an `if` (no trailing return) → some path returns no value.
        let module = IrModule {
            errors: vec![],
            functions: vec![IrFunction {
                name: "f".into(),
                params: vec![IrParam {
                    name: "b".into(),
                    ty: IrType::Bool,
                }],
                ret: IrType::F64,
                fallible: false,
                body: vec![IrStmt::If {
                    cond: IrExpr {
                        ty: IrType::Bool,
                        kind: IrExprKind::Var("b".into()),
                    },
                    body: vec![IrStmt::Return(IrExpr {
                        ty: IrType::F64,
                        kind: IrExprKind::ConstF64(1.0),
                    })],
                }],
            }],
        };
        let err = emit(&module).unwrap_err();
        assert!(
            err.message.contains("return on all paths"),
            "{}",
            err.message
        );
    }
}
