//! W4 codegen: typed IR → Rust source (`extern "C"` cdylib), then build to a DLL.
//!
//! Per D19 this is the **provisional rustc lowering**: emit Rust, `cargo build
//! --crate-type cdylib`. The IR is backend-independent, so a C-emit backend can be
//! added later without touching the front/middle end.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::ir::*;

#[derive(Debug, PartialEq, Eq, Clone)]
pub struct CodegenError {
    pub message: String,
}

impl CodegenError {
    pub fn new(message: impl Into<String>) -> Self {
        CodegenError {
            message: message.into(),
        }
    }
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "codegen error: {}", self.message)
    }
}

impl std::error::Error for CodegenError {}

/// Emit Rust source implementing the IR module as a C-ABI cdylib (D18 exports:
/// `mlx_<fn>` + reserved `ml_module_abi_version`).
pub fn emit(module: &IrModule) -> Result<String, CodegenError> {
    let mut out = String::new();
    out.push_str("// Generated by mlc. Do not edit.\n");
    out.push_str("#![no_std]\n");
    out.push_str("#![allow(unused_parens)]\n");
    // A surface `let mut` that is never reassigned is legal Mathless; don't make rustc
    // complain about the faithful lowering.
    out.push_str("#![allow(unused_mut)]\n\n");
    out.push_str("#[no_mangle]\n");
    // Interpolate the single-source ABI version (D18) so the emitted module can't drift.
    let _ = writeln!(
        out,
        "pub extern \"C\" fn ml_module_abi_version() -> u32 {{ {} }}\n",
        crate::abi::ML_MODULE_ABI_VERSION
    );

    for f in &module.functions {
        emit_function(f, &mut out)?;
        out.push('\n');
    }

    // A no_std cdylib requires a panic handler. Nothing on today's surface can reach this one:
    // `f64 /0` is inf, `as` saturates, integer arithmetic wraps (release leaves overflow-checks
    // off) and i32 `/`/`%` are emitted guarded below, so neither a zero divisor nor
    // `i32::MIN / -1` reaches a panicking operator. So it exists to satisfy `no_std`, not to
    // handle anything.
    //
    // What it does if a future slice DOES reach it matters, because it is easy to get wrong:
    // in `no_std` the `#[panic_handler]` IS the panic runtime, and the profile's
    // `panic = "abort"` only drops unwinding tables — it does not call abort(). So a panic
    // lands here and spins, hanging the calling host thread while the process stays up. That
    // is the `while` liveness class, not the recursion class (STATUS §5-4).
    out.push_str("#[panic_handler]\nfn ml_panic(_: &core::panic::PanicInfo) -> ! { loop {} }\n");
    Ok(out)
}

fn emit_function(f: &IrFunction, out: &mut String) -> Result<(), CodegenError> {
    if !block_always_returns(&f.body) {
        // Backend safety net: typeck rejects this for real source (see `typeck::check`), but
        // directly-built IR could still fall off the end without returning a typed value.
        return Err(CodegenError::new(format!(
            "function '{}' may not return on all paths",
            f.name
        )));
    }

    let mut params: Vec<String> = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, rust_type(p.ty)))
        .collect();

    // An internal function is a plain Rust `fn`: no `#[no_mangle]`, no `extern "C"`, no
    // `mlx_` prefix. That is what keeps it out of the export table — measured in acceptance
    // C, not asserted here (SPEC-calls section 2.3).
    if !f.exported {
        let _ = writeln!(
            out,
            "fn {}({}) -> {} {{",
            f.name,
            params.join(", "),
            rust_type(f.ret)
        );
        for s in &f.body {
            emit_stmt(s, 1, false, out);
        }
        out.push_str("}\n");
        return Ok(());
    }

    // `write!` into a String is infallible; the `_ =` documents that.
    out.push_str("#[no_mangle]\n");
    if f.fallible {
        // D17: a fallible fn returns an `i32` status and delivers its value through a
        // `*mut T` out-param appended after the declared parameters.
        params.push(format!("out_value: *mut {}", rust_type(f.ret)));
        let _ = writeln!(
            out,
            "pub extern \"C\" fn mlx_{}({}) -> i32 {{",
            f.name,
            params.join(", ")
        );
    } else {
        let _ = writeln!(
            out,
            "pub extern \"C\" fn mlx_{}({}) -> {} {{",
            f.name,
            params.join(", "),
            rust_type(f.ret)
        );
    }
    for s in &f.body {
        emit_stmt(s, 1, f.fallible, out);
    }
    out.push_str("}\n");
    Ok(())
}

fn rust_type(t: IrType) -> &'static str {
    match t {
        IrType::F64 => "f64",
        IrType::Bool => "bool",
        IrType::I32 => "i32",
    }
}

fn emit_stmt(s: &IrStmt, indent: usize, fallible: bool, out: &mut String) {
    let pad = "    ".repeat(indent);
    match s {
        IrStmt::Return(e) => {
            if fallible {
                // Success: write the value through the out-param, return status 0 (D17).
                let _ = writeln!(
                    out,
                    "{pad}unsafe {{ *out_value = {}; }} return 0;",
                    emit_expr(e)
                );
            } else {
                let _ = writeln!(out, "{pad}return {};", emit_expr(e));
            }
        }
        IrStmt::Fail(code) => {
            // Failure: return the positive domain code; the out-param is left untouched.
            let _ = writeln!(out, "{pad}return {code};");
        }
        IrStmt::Let {
            name,
            value,
            mutable,
        } => {
            // Internal binding — a plain Rust `let`, never an export.
            let kw = if *mutable { "let mut" } else { "let" };
            let _ = writeln!(out, "{pad}{kw} {name} = {};", emit_expr(value));
        }
        IrStmt::Assign { name, value } => {
            // Reassign an in-scope `let mut`. Inside an `if` this mutates the OUTER binding,
            // which is the point of the slice: `if` is a statement, so a mutable local is how
            // a branch result is collected.
            let _ = writeln!(out, "{pad}{name} = {};", emit_expr(value));
        }
        IrStmt::If { cond, body } => {
            let _ = writeln!(out, "{pad}if {} {{", emit_expr(cond));
            for st in body {
                emit_stmt(st, indent + 1, fallible, out);
            }
            let _ = writeln!(out, "{pad}}}");
        }
        IrStmt::While { cond, body } => {
            // A module export may now fail to return (SPEC-while §5.1). There is nothing to
            // emit for that: no fuel counter without the VM R01 rejected, no timeout without a
            // runtime. The contract is documented in HOST_ABI instead.
            let _ = writeln!(out, "{pad}while {} {{", emit_expr(cond));
            for st in body {
                emit_stmt(st, indent + 1, fallible, out);
            }
            let _ = writeln!(out, "{pad}}}");
        }
    }
}

fn emit_expr(e: &IrExpr) -> String {
    match &e.kind {
        IrExprKind::ConstF64(n) => format!("{n:?}f64"),
        IrExprKind::ConstI32(n) => format!("{n}i32"),
        IrExprKind::ConstBool(b) => b.to_string(),
        IrExprKind::Var(name) => name.clone(),
        IrExprKind::Call { name, args } => {
            let args: Vec<String> = args.iter().map(emit_expr).collect();
            format!("{name}({})", args.join(", "))
        }
        IrExprKind::Cast { to, operand } => {
            // Backend net for directly-built IR, and this one guards a *silent* failure:
            // Rust accepts `bool as i32` and yields 0/1, so hand-built IR would compile and
            // quietly mean something Mathless forbids. (`bool as f64` is a rustc error, so
            // that half is loud on its own.) Source cannot reach here — typeck rejects it.
            debug_assert!(
                operand.ty != IrType::Bool && *to != IrType::Bool,
                "IrExprKind::Cast involving bool ({:?} as {to:?}): `as` is numeric-only",
                operand.ty
            );
            // Rust's `as` truncates toward zero, saturates out-of-range, and maps NaN to 0 —
            // exactly the semantics the SPEC pins. That agreement is why this lowering is one
            // line; it is NOT the reason the semantics were chosen, and a C backend must
            // implement them by hand (C casts are UB out of range).
            format!("({} as {})", emit_expr(operand), rust_type(*to))
        }
        IrExprKind::Unary { op, operand } => {
            // Backend safety net for directly-built IR, in the same spirit as
            // `block_always_returns`: Rust's `!` is a *bitwise* complement on integers, so
            // emitting `Not` on a non-bool would silently mean something else. Source can't
            // get here — typeck rejects it — but the IR is a public type (Grok verify).
            debug_assert!(
                !matches!(op, IrUnOp::Not) || operand.ty == IrType::Bool,
                "IrUnOp::Not on {:?}: Rust's `!` is bitwise on integers",
                operand.ty
            );
            // Parenthesised like the binary case, so precedence never depends on the target
            // language's table. Rust's unary binds tighter than `*` anyway; this makes it
            // explicit and survives a future C backend unchanged.
            let sym = match op {
                IrUnOp::Neg => "-",
                IrUnOp::Not => "!",
            };
            format!("({sym}{})", emit_expr(operand))
        }
        IrExprKind::Binary { op, lhs, rhs } => {
            // Directly-built IR could put `&&`/`||` on non-bool operands. Note this is a
            // *weaker* hazard than `IrUnOp::Not` on an integer: Rust's `&&` is bool-only, so
            // that would fail when the generated crate compiles rather than silently meaning
            // something else. The assert just moves the failure somewhere legible.
            debug_assert!(
                !matches!(op, IrBinOp::And | IrBinOp::Or)
                    || (lhs.ty == IrType::Bool && rhs.ty == IrType::Bool),
                "IrBinOp::{op:?} on {:?} and {:?}: logical operators are bool-only",
                lhs.ty,
                rhs.ty
            );
            // i32 `/` and `%` are TOTAL in Mathless (SPEC-i32-division DP-D1), and Rust's are
            // not: the plain operator panics on `b == 0` and, separately, on `i32::MIN / -1`.
            // The second one is easy to miss — division overflow panics in a release build too,
            // because it is NOT governed by `overflow-checks` (measured with
            // `rustc -O -C overflow-checks=off`). Either panic would enter `ml_panic` and spin
            // there, hanging the host thread (STATUS §5-4), so both edges close here:
            // `wrapping_*` handles MIN/-1 and the guard handles the zero.
            //
            // The divisor is bound first so it is evaluated exactly once — `a / f(b)` must not
            // call `f` twice just because the emitted form mentions the divisor in two places.
            if matches!(op, IrBinOp::Div | IrBinOp::Rem) && lhs.ty == IrType::I32 {
                let method = if matches!(op, IrBinOp::Div) {
                    "wrapping_div"
                } else {
                    "wrapping_rem"
                };
                return format!(
                    "{{ let __d = {}; if __d == 0 {{ 0i32 }} else {{ ({}).{}(__d) }} }}",
                    emit_expr(rhs),
                    emit_expr(lhs),
                    method
                );
            }
            format!("({} {} {})", emit_expr(lhs), op_str(*op), emit_expr(rhs))
        }
    }
}

fn op_str(op: IrBinOp) -> &'static str {
    match op {
        IrBinOp::Add => "+",
        IrBinOp::Sub => "-",
        IrBinOp::Mul => "*",
        // `Div` reaches here only for f64; the i32 form is emitted guarded above and never
        // takes this path. `Rem` is i32-only (DP-D4), so it never reaches here at all —
        // the arm exists so a future f64 `%` cannot be added without noticing this.
        IrBinOp::Div => "/",
        IrBinOp::Rem => "%",
        IrBinOp::Lt => "<",
        IrBinOp::Gt => ">",
        IrBinOp::Le => "<=",
        IrBinOp::Ge => ">=",
        IrBinOp::Eq => "==",
        IrBinOp::Ne => "!=",
        // Rust's `&&`/`||` short-circuit, which is what SPEC-logical-ops DP-B2 specifies.
        // Nothing in the language can observe that yet (no calls, no trapping operations),
        // so the SPEC records it as specified-but-unmeasured rather than claiming a test.
        IrBinOp::And => "&&",
        IrBinOp::Or => "||",
    }
}

/// Write `rust_src` as a `cdylib` crate under `workdir/<crate_name>` and build it,
/// returning the produced DLL path. Requires `cargo` on PATH (D19/D20). Windows target
/// (D22): the artifact is `<crate_name>.dll`.
///
/// This is a caller-supplied-dir primitive: the caller must pass a **unique** `workdir` per
/// concurrent invocation (`emit_artifacts` uses a private temp tree; the oracle tests
/// namespace theirs per process). Two calls sharing a `workdir` would race.
pub fn build_cdylib(
    rust_src: &str,
    crate_name: &str,
    workdir: &Path,
) -> Result<PathBuf, CodegenError> {
    let crate_dir = workdir.join(crate_name);
    std::fs::create_dir_all(crate_dir.join("src"))
        .map_err(|e| CodegenError::new(format!("create crate dir: {e}")))?;
    std::fs::write(
        crate_dir.join("Cargo.toml"),
        format!(
            "[package]\nname = \"{crate_name}\"\nversion = \"0.0.0\"\nedition = \"2021\"\npublish = false\n\n[lib]\ncrate-type = [\"cdylib\"]\n\n[profile.release]\npanic = \"abort\"\nstrip = true\nlto = true\nopt-level = \"z\"\n"
        ),
    )
    .map_err(|e| CodegenError::new(format!("write Cargo.toml: {e}")))?;
    std::fs::write(crate_dir.join("src").join("lib.rs"), rust_src)
        .map_err(|e| CodegenError::new(format!("write lib.rs: {e}")))?;

    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".into());
    let status = Command::new(cargo)
        .args(["build", "--release", "--manifest-path"])
        .arg(crate_dir.join("Cargo.toml"))
        .status()
        .map_err(|e| CodegenError::new(format!("spawn cargo: {e}")))?;
    if !status.success() {
        return Err(CodegenError::new("cargo build of generated crate failed"));
    }

    let dll = crate_dir
        .join("target")
        .join("release")
        .join(format!("{crate_name}.dll"));
    if !dll.exists() {
        return Err(CodegenError::new(format!(
            "expected dll not found: {}",
            dll.display()
        )));
    }
    Ok(dll)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compile_to_ir;

    #[test]
    fn emit_discount_produces_extern_c_rust() {
        let ir = compile_to_ir(include_str!("../../examples/discount.mls")).unwrap();
        let rust = emit(&ir).expect("emit");
        assert!(
            rust.contains(r#"pub extern "C" fn mlx_discount(price: f64, vip: bool) -> f64"#),
            "{rust}"
        );
        assert!(rust.contains("#![no_std]"), "{rust}");
        assert!(rust.contains("ml_module_abi_version"), "{rust}");
        assert!(rust.contains("if vip"), "{rust}");
        assert!(rust.contains("return price"), "{rust}");
    }

    #[test]
    fn rejects_function_without_guaranteed_return() {
        // Only statement is an `if` (no trailing return) → some path returns no value.
        let module = IrModule {
            errors: vec![],
            functions: vec![IrFunction {
                name: "f".into(),
                params: vec![IrParam {
                    name: "b".into(),
                    ty: IrType::Bool,
                }],
                ret: IrType::F64,
                fallible: false,
                exported: true,
                body: vec![IrStmt::If {
                    cond: IrExpr {
                        ty: IrType::Bool,
                        kind: IrExprKind::Var("b".into()),
                    },
                    body: vec![IrStmt::Return(IrExpr {
                        ty: IrType::F64,
                        kind: IrExprKind::ConstF64(1.0),
                    })],
                }],
            }],
        };
        let err = emit(&module).unwrap_err();
        assert!(
            err.message.contains("return on all paths"),
            "{}",
            err.message
        );
    }
}
