//! W4 codegen: typed IR → Rust source (`extern "C"` cdylib), then build to a DLL.
//!
//! Per D19 this is the **provisional rustc lowering**: emit Rust, `cargo build
//! --crate-type cdylib`. The IR is backend-independent, so a C-emit backend can be
//! added later without touching the front/middle end.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::ir::*;

#[derive(Debug, PartialEq, Eq, Clone)]
pub struct CodegenError {
    pub message: String,
}

impl CodegenError {
    pub fn new(message: impl Into<String>) -> Self {
        CodegenError {
            message: message.into(),
        }
    }
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "codegen error: {}", self.message)
    }
}

impl std::error::Error for CodegenError {}

/// Emit Rust source implementing the IR module as a C-ABI cdylib (D18 exports:
/// `mlx_<fn>` + reserved `ml_module_abi_version`).
pub fn emit(module: &IrModule) -> Result<String, CodegenError> {
    let mut out = String::new();
    out.push_str("// Generated by mlc. Do not edit.\n");
    out.push_str("#![no_std]\n");
    out.push_str("#![allow(unused_parens)]\n");
    // A surface `let mut` that is never reassigned is legal Mathless; don't make rustc
    // complain about the faithful lowering.
    out.push_str("#![allow(unused_mut)]\n\n");
    out.push_str("#[no_mangle]\n");
    // Interpolate the single-source ABI version (D18) so the emitted module can't drift.
    let _ = writeln!(
        out,
        "pub extern \"C\" fn ml_module_abi_version() -> u32 {{ {} }}\n",
        crate::abi::ML_MODULE_ABI_VERSION
    );

    emit_string_helper(module, &mut out);
    emit_strout_helper(module, &mut out);
    emit_rounding_helpers(module, &mut out);

    for f in &module.functions {
        emit_function(f, &mut out)?;
        out.push('\n');
    }

    // A no_std cdylib requires a panic handler. Nothing on today's surface can reach this one:
    // `f64 /0` is inf, `as` saturates, integer arithmetic wraps (release leaves overflow-checks
    // off) and i32 `/`/`%` are emitted guarded below, so neither a zero divisor nor
    // `i32::MIN / -1` reaches a panicking operator. So it exists to satisfy `no_std`, not to
    // handle anything.
    //
    // What it does if a future slice DOES reach it matters, because it is easy to get wrong:
    // in `no_std` the `#[panic_handler]` IS the panic runtime, and the profile's
    // `panic = "abort"` only drops unwinding tables — it does not call abort(). So a panic
    // lands here and spins, hanging the calling host thread while the process stays up. That
    // is the `while` liveness class, not the recursion class (STATUS §5-4).
    out.push_str("#[panic_handler]\nfn ml_panic(_: &core::panic::PanicInfo) -> ! { loop {} }\n");
    Ok(out)
}

fn emit_function(f: &IrFunction, out: &mut String) -> Result<(), CodegenError> {
    if !block_always_returns(&f.body) {
        // Backend safety net: typeck rejects this for real source (see `typeck::check`), but
        // directly-built IR could still fall off the end without returning a typed value.
        return Err(CodegenError::new(format!(
            "function '{}' may not return on all paths",
            f.name
        )));
    }

    // Declared `out` params become `*mut T`, in source order — in the BODY as well as in the
    // adapter, so the adapter forwards the pointer rather than re-deriving it.
    let params: Vec<String> = f
        .params
        .iter()
        .map(|p| {
            if p.out {
                format!("{}: *mut {}", p.name, rust_type(p.ty))
            } else {
                format!("{}: {}", p.name, rust_type(p.ty))
            }
        })
        .collect();

    // ── The body. Every Mathless function has exactly one, and it is a plain Rust `fn`
    // (SPEC-export-wrappers DP-W1). It carries the Rust-native shape: `T` when infallible,
    // `Result<T, i32>` when fallible.
    //
    // The name is `ml_fn_<name>`, never the user's own. `ml_` is already reserved from user
    // identifiers (#85), so no user name reaches the generated Rust as a function — which is
    // why `export fn type` and `export fn match` keep compiling (measured: they compile today
    // only because the `mlx_` prefix hides them from rustc's keyword list) and why the
    // internal-name reserved-word check loses its reason to exist.
    let (body_ret, abi) = if f.fallible {
        (
            format!("Result<{}, i32>", rust_type(f.ret)),
            RetAbi::Fallible,
        )
    } else {
        (rust_type(f.ret).to_string(), RetAbi::Plain)
    };
    let _ = writeln!(
        out,
        "fn ml_fn_{}({}) -> {} {{",
        f.name,
        params.join(", "),
        body_ret
    );
    for s in &f.body {
        emit_stmt(s, 1, abi, out);
    }
    out.push_str("}\n");

    // An internal function stops here: no `#[no_mangle]`, so it never reaches the export
    // table (measured in acceptance C, not asserted here).
    if !f.exported {
        return Ok(());
    }

    // ── The adapter. This is the ONLY place the C ABI is spoken, and it contains no logic:
    // it forwards the arguments, then converts the body's Rust-native result into D17's
    // status + out-param or Q12's buffer triple.
    //
    // DP-W2 puts it immediately after its body, so the two halves of one function read
    // together.
    let args: Vec<&str> = f.params.iter().map(|p| p.name.as_str()).collect();
    let call = format!("ml_fn_{}({})", f.name, args.join(", "));
    let mut sig = params;

    out.push_str("#[no_mangle]\n");
    if f.ret == IrType::Str {
        // Q12: the module never allocates; `ml_strout` copies into the host's buffer and
        // returns the status. Truncation is a failure, and it writes nothing (DP-T2).
        sig.push("ml_buf: *mut u8".to_string());
        sig.push("ml_cap: i32".to_string());
        sig.push("ml_needed: *mut i32".to_string());
        let _ = writeln!(
            out,
            "pub extern \"C\" fn mlx_{}({}) -> i32 {{",
            f.name,
            sig.join(", ")
        );
        let _ = writeln!(
            out,
            "    match {call} {{ Ok(__v) => ml_strout(__v, ml_buf, ml_cap, ml_needed), Err(__e) => __e }}"
        );
    } else if f.fallible {
        // D17: an `i32` status return plus a `*mut T` out-param, appended after every
        // declared out (DP-O1 — the return value is always last).
        //
        // `*out_value` is written ONLY on the success arm. Writing it first and choosing the
        // status afterwards would compile, would keep the status correct, and would clobber
        // the host's variable on the failure path — which DP-E3 says the host may then read
        // as untouched.
        sig.push(format!("out_value: *mut {}", rust_type(f.ret)));
        let _ = writeln!(
            out,
            "pub extern \"C\" fn mlx_{}({}) -> i32 {{",
            f.name,
            sig.join(", ")
        );
        let _ = writeln!(
            out,
            "    match {call} {{ Ok(__v) => {{ unsafe {{ *out_value = __v; }} 0 }} Err(__e) => __e }}"
        );
    } else {
        // Infallible: the value IS the C return, so the adapter is a forwarding call.
        let _ = writeln!(
            out,
            "pub extern \"C\" fn mlx_{}({}) -> {} {{",
            f.name,
            sig.join(", "),
            rust_type(f.ret)
        );
        let _ = writeln!(out, "    {call}");
    }
    out.push_str("}\n");
    Ok(())
}

fn rust_type(t: IrType) -> &'static str {
    match t {
        // Borrowed for the call (D16 rule 1). NUL-terminated, never owned, never allocated.
        IrType::Str => "*const u8",
        IrType::F64 => "f64",
        IrType::Bool => "bool",
        IrType::I32 => "i32",
    }
}

/// How a function BODY returns. Only two shapes, because a body never speaks the C ABI —
/// that lives in the adapter (SPEC-export-wrappers).
///
/// This used to have four variants, two of them C-facing (`Status` for D17's status +
/// out-param, `StringBuffer` for Q12's triple). Splitting exports into a body plus an adapter
/// deleted both: `return` and `fail` now lower one way for an infallible function and one way
/// for a fallible one, whether or not anyone exports it.
#[derive(Clone, Copy, PartialEq, Eq)]
enum RetAbi {
    /// Infallible: `return e` is `return e`.
    Plain,
    /// Fallible: `Result<T, i32>` — the only shape needing no invented value on the failure
    /// path (DP-F6). `Option` would lose the D17 code.
    Fallible,
}

impl RetAbi {
    /// How a propagating failure leaves a body with this shape.
    fn propagate(self) -> &'static str {
        match self {
            RetAbi::Fallible => "return Err(__e)",
            // Unreachable from source: typeck requires a `try` caller to be fallible. Kept
            // total so hand-built IR cannot fall through to something worse.
            RetAbi::Plain => "return __e",
        }
    }
}

fn emit_stmt(s: &IrStmt, indent: usize, abi: RetAbi, out: &mut String) {
    let pad = "    ".repeat(indent);
    match s {
        IrStmt::Return(e) => match abi {
            // A fallible body hands its value back as `Ok`, so its caller — the adapter, or
            // another Mathless function through `try` — can tell success from a propagated
            // status without a sentinel value.
            RetAbi::Fallible => {
                let _ = writeln!(out, "{pad}return Ok({});", emit_expr(e));
            }
            RetAbi::Plain => {
                let _ = writeln!(out, "{pad}return {};", emit_expr(e));
            }
        },
        IrStmt::Fail(code) => {
            // The domain code, wrapped so it survives the hop to whoever unwraps it. Emitting
            // a bare `return <code>` here is exactly the silent wrong answer #67 measured: for
            // `-> i32!` the code came back as an ordinary value.
            if abi == RetAbi::Fallible {
                let _ = writeln!(out, "{pad}return Err({code});");
            } else {
                // Unreachable from source — `fail` requires a fallible function.
                let _ = writeln!(out, "{pad}return {code};");
            }
        }
        // `<dest> = try <callee>(<args>)`.
        //
        // Lowered as a `match`, never with Rust's `?`: `?` only works inside a function
        // returning `Result`, and two of the three C-facing shapes return a bare `i32`, so it
        // would need a nested inner fn per export. One `match` fits all four ABIs.
        //
        // `__v` and `__e` are ARM-LOCAL, so no two statements' temporaries can collide — the
        // `__d` shadowing defect (#85) came from a temporary that outlived its arm. `__` is
        // reserved from user identifiers anyway, which is the second line of defence.
        IrStmt::TryCall {
            dest, callee, args, ..
        } => {
            let call = format!(
                "ml_fn_{callee}({})",
                args.iter().map(emit_expr).collect::<Vec<_>>().join(", ")
            );
            let prop = abi.propagate();
            match dest {
                IrTryDest::Let { name, mutable } => {
                    let m = if *mutable { "mut " } else { "" };
                    let _ = writeln!(
                        out,
                        "{pad}let {m}{name} = match {call} {{ Ok(__v) => __v, Err(__e) => {prop} }};"
                    );
                }
                IrTryDest::Assign(name) => {
                    let _ = writeln!(
                        out,
                        "{pad}{name} = match {call} {{ Ok(__v) => __v, Err(__e) => {prop} }};"
                    );
                }
                // A write THROUGH a pointer, exactly like `IrStmt::AssignOut`. Emitting a
                // plain `name = …` here would assign the pointer itself.
                IrTryDest::AssignOut(name) => {
                    let _ = writeln!(
                        out,
                        "{pad}unsafe {{ *{name} = match {call} {{ Ok(__v) => __v, Err(__e) => {prop} }}; }}"
                    );
                }
                // `return try f(x)`: the success arm has to do whatever this function's own
                // `return` does, so it is delegated rather than duplicated — emitted INSIDE
                // the arm so `__v` stays arm-local like the other three destinations. Binding
                // it outside would work today (this statement always ends its block) but it
                // is the shape the `__d` defect came from, and there is no reason to keep it.
                IrTryDest::Return => {
                    let _ = writeln!(out, "{pad}match {call} {{");
                    let _ = writeln!(out, "{pad}    Ok(__v) => {{");
                    emit_stmt(
                        &IrStmt::Return(IrExpr {
                            // The type is not read by any `Return` arm — the emitted
                            // expression is the binding `__v`, whose type rustc infers from
                            // the callee's `Result`.
                            ty: IrType::I32,
                            kind: IrExprKind::Var("__v".to_string()),
                        }),
                        indent + 2,
                        abi,
                        out,
                    );
                    let _ = writeln!(out, "{pad}    }}");
                    let _ = writeln!(out, "{pad}    Err(__e) => {{ {prop}; }}");
                    let _ = writeln!(out, "{pad}}}");
                }
            }
        }
        IrStmt::Let {
            name,
            value,
            mutable,
        } => {
            // Internal binding — a plain Rust `let`, never an export.
            let kw = if *mutable { "let mut" } else { "let" };
            let _ = writeln!(out, "{pad}{kw} {name} = {};", emit_expr(value));
        }
        IrStmt::AssignOut { name, value } => {
            // Same shape as the D17 success write: a raw store through the caller's pointer.
            // The host contract is that the pointer is valid for the duration of the call
            // (D16); a NULL is undefined behaviour here exactly as it already is for
            // `out_value` (SPEC-out-params section 5.1 — inherited, not introduced).
            let _ = writeln!(out, "{pad}unsafe {{ *{name} = {}; }}", emit_expr(value));
        }
        IrStmt::Assign { name, value } => {
            // Reassign an in-scope `let mut`. Inside an `if` this mutates the OUTER binding,
            // which is the point of the slice: `if` is a statement, so a mutable local is how
            // a branch result is collected.
            let _ = writeln!(out, "{pad}{name} = {};", emit_expr(value));
        }
        IrStmt::If { cond, body } => {
            let _ = writeln!(out, "{pad}if {} {{", emit_expr(cond));
            for st in body {
                emit_stmt(st, indent + 1, abi, out);
            }
            let _ = writeln!(out, "{pad}}}");
        }
        IrStmt::While { cond, body } => {
            // A module export may now fail to return (SPEC-while §5.1). There is nothing to
            // emit for that: no fuel counter without the VM R01 rejected, no timeout without a
            // runtime. The contract is documented in HOST_ABI instead.
            let _ = writeln!(out, "{pad}while {} {{", emit_expr(cond));
            for st in body {
                emit_stmt(st, indent + 1, abi, out);
            }
            let _ = writeln!(out, "{pad}}}");
        }
    }
}

fn emit_expr(e: &IrExpr) -> String {
    match &e.kind {
        // A static, NUL-terminated byte array: no allocation, and the NUL makes the module's
        // view of the bytes identical to the C caller's (DP-S1).
        IrExprKind::ConstStr(s) => format!("b\"{s}\\0\".as_ptr()"),
        IrExprKind::ConstF64(n) => format!("{n:?}f64"),
        IrExprKind::ConstI32(n) => format!("{n}i32"),
        IrExprKind::ConstBool(b) => b.to_string(),
        IrExprKind::Var(name) => name.clone(),
        IrExprKind::Call { name, args } => {
            let args: Vec<String> = args.iter().map(emit_expr).collect();
            // A built-in rounder lowers to its `ml_`-prefixed helper (emitted above). That is
            // safe because `reserved::generated_prefix` rejects `ml_` on PARAMETERS and
            // LOCALS, which are still emitted raw — when this comment once claimed the prefix
            // was "already reserved" it was only true of function names, and
            // `export fn f(ml_floor: f64) -> f64 { return floor(ml_floor) }` emitted
            // `ml_floor(ml_floor)` and died in rustc (#85).
            //
            // Function names no longer need the rule: since the wrapper refactor a user
            // function is `ml_fn_<name>`, which cannot collide with `ml_floor` (DP-W4).
            if crate::typeck::BUILTIN_ROUNDERS.contains(&name.as_str()) {
                format!("ml_{name}({})", args.join(", "))
            } else {
                // Every Mathless function is one body named `ml_fn_<name>`, exported or not,
                // so a call site no longer has to know which it is. Before the wrapper
                // refactor this branch chose between `mlx_<name>` and the bare name, and
                // choosing wrong meant the generated crate did not build (#95).
                format!("ml_fn_{name}({})", args.join(", "))
            }
        }
        IrExprKind::Cast { to, operand } => {
            // Backend net for directly-built IR, and this one guards a *silent* failure:
            // Rust accepts `bool as i32` and yields 0/1, so hand-built IR would compile and
            // quietly mean something Mathless forbids. (`bool as f64` is a rustc error, so
            // that half is loud on its own.) Source cannot reach here — typeck rejects it.
            debug_assert!(
                operand.ty != IrType::Bool && *to != IrType::Bool,
                "IrExprKind::Cast involving bool ({:?} as {to:?}): `as` is numeric-only",
                operand.ty
            );
            // Rust's `as` truncates toward zero, saturates out-of-range, and maps NaN to 0 —
            // exactly the semantics the SPEC pins. That agreement is why this lowering is one
            // line; it is NOT the reason the semantics were chosen, and a C backend must
            // implement them by hand (C casts are UB out of range).
            format!("({} as {})", emit_expr(operand), rust_type(*to))
        }
        IrExprKind::Unary { op, operand } => {
            // Backend safety net for directly-built IR, in the same spirit as
            // `block_always_returns`: Rust's `!` is a *bitwise* complement on integers, so
            // emitting `Not` on a non-bool would silently mean something else. Source can't
            // get here — typeck rejects it — but the IR is a public type (Grok verify).
            debug_assert!(
                !matches!(op, IrUnOp::Not) || operand.ty == IrType::Bool,
                "IrUnOp::Not on {:?}: Rust's `!` is bitwise on integers",
                operand.ty
            );
            // Parenthesised like the binary case, so precedence never depends on the target
            // language's table. Rust's unary binds tighter than `*` anyway; this makes it
            // explicit and survives a future C backend unchanged.
            let sym = match op {
                IrUnOp::Neg => "-",
                IrUnOp::Not => "!",
            };
            format!("({sym}{})", emit_expr(operand))
        }
        IrExprKind::Binary { op, lhs, rhs } => {
            // Directly-built IR could put `&&`/`||` on non-bool operands. Note this is a
            // *weaker* hazard than `IrUnOp::Not` on an integer: Rust's `&&` is bool-only, so
            // that would fail when the generated crate compiles rather than silently meaning
            // something else. The assert just moves the failure somewhere legible.
            debug_assert!(
                !matches!(op, IrBinOp::And | IrBinOp::Or)
                    || (lhs.ty == IrType::Bool && rhs.ty == IrType::Bool),
                "IrBinOp::{op:?} on {:?} and {:?}: logical operators are bool-only",
                lhs.ty,
                rhs.ty
            );
            // i32 `/` and `%` are TOTAL in Mathless (SPEC-i32-division DP-D1), and Rust's are
            // not: the plain operator panics on `b == 0` and, separately, on `i32::MIN / -1`.
            // The second one is easy to miss — division overflow panics in a release build too,
            // because it is NOT governed by `overflow-checks` (measured with
            // `rustc -O -C overflow-checks=off`). Either panic would enter `ml_panic` and spin
            // there, hanging the host thread (STATUS §5-4), so both edges close here:
            // `wrapping_*` handles MIN/-1 and the guard handles the zero.
            //
            // The divisor is bound first so it is evaluated exactly once — `a / f(b)` must not
            // call `f` twice just because the emitted form mentions the divisor in two places.
            if matches!(op, IrBinOp::Div | IrBinOp::Rem) && lhs.ty == IrType::I32 {
                let method = if matches!(op, IrBinOp::Div) {
                    "wrapping_div"
                } else {
                    "wrapping_rem"
                };
                return format!(
                    "{{ let __d = {}; if __d == 0 {{ 0i32 }} else {{ ({}).{}(__d) }} }}",
                    emit_expr(rhs),
                    emit_expr(lhs),
                    method
                );
            }
            // A string is a `*const u8` (DP-S1). Rust's `==` on raw pointers compares the
            // ADDRESSES, which would make `country == "KR"` false for a host string that
            // happens to hold exactly those bytes — the wrong answer, silently, with no
            // compile error. Route both directions through the byte-loop helper instead.
            if matches!(op, IrBinOp::Eq | IrBinOp::Ne) && lhs.ty == IrType::Str {
                let call = format!("ml_streq({}, {})", emit_expr(lhs), emit_expr(rhs));
                return if matches!(op, IrBinOp::Eq) {
                    call
                } else {
                    format!("(!{call})")
                };
            }
            format!("({} {} {})", emit_expr(lhs), op_str(*op), emit_expr(rhs))
        }
    }
}

/// Copy a NUL-terminated string into the host's buffer, per the Q12 protocol
/// (SPEC-string-return section 2).
///
/// Every hazard this slice has lives in these fifteen lines, so each rule is written down
/// next to the code that keeps it:
///
/// - **Two passes.** The length is counted BEFORE anything is copied, because Q12 says a
///   truncated call leaves `buf` untouched — and with no allocator there is nowhere to stage
///   a partial result. DP-T2 confirmed that table unchanged, so this is load-bearing, not a
///   convenience.
/// - **One unit everywhere.** `cap` and `*needed` are total bytes INCLUDING the NUL, on every
///   path (DP-T4). That makes the host's retry exactly `cap = *needed`, and it makes
///   `*needed == 0` impossible — so 0 can never be confused with an empty string, which is 1.
/// - **`cap < n` covers `cap == 0` and `cap < 0`.** `n` is at least 1 (an empty string still
///   needs its NUL), so a zero or negative capacity is truncation by the same comparison as
///   any other. Nothing is reinterpreted as unsigned — MSVC documents exactly that overrun
///   for `_snprintf` with a negative count.
/// - **`buf` is only dereferenced after that check**, which is what makes the `cap == 0`
///   probe safe with a NULL buffer (DP-T7). The probe is the documented way to learn the
///   length, so it must be safe, not merely tolerated.
/// - **No slicing, no indexing, no bounds check.** Raw `ptr::add` only. A panic in a
///   generated module enters `ml_panic`'s `loop {}` and hangs the calling host thread rather
///   than crashing (STATUS section 5-4), so the goal is code that cannot panic at all.
fn emit_strout_helper(module: &IrModule, out: &mut String) {
    if !module
        .functions
        .iter()
        .any(|f| f.exported && f.ret == IrType::Str)
    {
        return;
    }
    out.push_str(
        "fn ml_strout(src: *const u8, buf: *mut u8, cap: i32, needed: *mut i32) -> i32 {\n\
         \x20   // Pass 1: count to the NUL, inclusive. `n` ends at >= 1 for every string.\n\
         \x20   let mut n: i32 = 0;\n\
         \x20   loop {\n\
         \x20       let b = unsafe { *src.add(n as usize) };\n\
         \x20       n += 1;\n\
         \x20       if b == 0 { break; }\n\
         \x20   }\n\
         \x20   unsafe { *needed = n; }\n\
         \x20   // Truncation is a FAILURE, not a short success (Q12). Nothing has been\n\
         \x20   // written, and nothing will be.\n\
         \x20   if cap < n { return -1; }\n\
         \x20   // Pass 2: copy, terminator included.\n\
         \x20   let mut i: i32 = 0;\n\
         \x20   while i < n {\n\
         \x20       unsafe { *buf.add(i as usize) = *src.add(i as usize); }\n\
         \x20       i += 1;\n\
         \x20   }\n\
         \x20   0\n\
         }\n\n",
    );
}

/// Does this module compare strings anywhere? Only then is the helper emitted.
fn compares_strings(module: &IrModule) -> bool {
    fn in_expr(e: &IrExpr) -> bool {
        match &e.kind {
            IrExprKind::Binary { op, lhs, rhs } => {
                (matches!(op, IrBinOp::Eq | IrBinOp::Ne) && lhs.ty == IrType::Str)
                    || in_expr(lhs)
                    || in_expr(rhs)
            }
            IrExprKind::Unary { operand, .. } | IrExprKind::Cast { operand, .. } => {
                in_expr(operand)
            }
            IrExprKind::Call { args, .. } => args.iter().any(in_expr),
            _ => false,
        }
    }
    fn in_stmts(body: &[IrStmt]) -> bool {
        body.iter().any(|s| match s {
            IrStmt::If { cond, body } | IrStmt::While { cond, body } => {
                in_expr(cond) || in_stmts(body)
            }
            IrStmt::Return(e)
            | IrStmt::Let { value: e, .. }
            | IrStmt::Assign { value: e, .. }
            | IrStmt::AssignOut { value: e, .. } => in_expr(e),
            // A try-call's arguments are ordinary expressions and may compare strings.
            IrStmt::TryCall { args, .. } => args.iter().any(in_expr),
            IrStmt::Fail(_) => false,
        })
    }
    module.functions.iter().any(|f| in_stmts(&f.body))
}

/// Byte-equality for two NUL-terminated pointers (SPEC-string-input section 2.3).
///
/// Deliberately NOT `strcmp`: calling the CRT would add an import, and the module's import set
/// is one of the protection proxies acceptance C measures (D04/D05). A byte loop costs a few
/// lines and keeps the boundary unchanged.
///
/// Encoding is opaque (DP-S2). Equal bytes are equal strings; matching encodings between host
/// and source is a host contract, stated in HOST_ABI.
fn emit_string_helper(module: &IrModule, out: &mut String) {
    if !compares_strings(module) {
        return;
    }
    out.push_str(
        "fn ml_streq(a: *const u8, b: *const u8) -> bool {\n\
         \x20   let mut i = 0usize;\n\
         \x20   loop {\n\
         \x20       let (x, y) = unsafe { (*a.add(i), *b.add(i)) };\n\
         \x20       if x != y { return false; }\n\
         \x20       if x == 0 { return true; }\n\
         \x20       i += 1;\n\
         \x20   }\n\
         }\n\n",
    );
}

/// Which built-in rounders this module actually calls, so an unused one is not emitted.
fn used_rounders(module: &IrModule) -> Vec<&'static str> {
    fn walk_expr(e: &IrExpr, found: &mut Vec<&'static str>) {
        match &e.kind {
            IrExprKind::Call { name, args, .. } => {
                if let Some(b) = crate::typeck::BUILTIN_ROUNDERS
                    .iter()
                    .find(|b| **b == name.as_str())
                {
                    if !found.contains(b) {
                        found.push(b);
                    }
                }
                for a in args {
                    walk_expr(a, found);
                }
            }
            IrExprKind::Unary { operand, .. } | IrExprKind::Cast { operand, .. } => {
                walk_expr(operand, found)
            }
            IrExprKind::Binary { lhs, rhs, .. } => {
                walk_expr(lhs, found);
                walk_expr(rhs, found);
            }
            IrExprKind::ConstF64(_)
            | IrExprKind::ConstI32(_)
            | IrExprKind::ConstBool(_)
            | IrExprKind::ConstStr(_)
            | IrExprKind::Var(_) => {}
        }
    }
    fn walk_stmts(body: &[IrStmt], found: &mut Vec<&'static str>) {
        for s in body {
            match s {
                IrStmt::If { cond, body } | IrStmt::While { cond, body } => {
                    walk_expr(cond, found);
                    walk_stmts(body, found);
                }
                IrStmt::Return(e)
                | IrStmt::Let { value: e, .. }
                | IrStmt::Assign { value: e, .. }
                | IrStmt::AssignOut { value: e, .. } => walk_expr(e, found),
                // Same for the rounding builtins: a try-call argument may use one, and
                // missing it here would emit a call to a helper that was never defined.
                IrStmt::TryCall { args, .. } => {
                    for a in args {
                        walk_expr(a, found);
                    }
                }
                IrStmt::Fail(_) => {}
            }
        }
    }
    let mut found = Vec::new();
    for f in &module.functions {
        walk_stmts(&f.body, &mut found);
    }
    found
}

/// Emit the rounding helpers this module needs (SPEC-rounding section 2.4).
///
/// `f64::floor` and friends live in `std`, not `core`, so a `no_std` cdylib cannot call them —
/// and taking `libm` would end this repo's zero-third-party-dependency property. These are
/// written with core operations only and are bit-exact with `std` (measured, including the
/// sign of zero).
fn emit_rounding_helpers(module: &IrModule, out: &mut String) {
    let used = used_rounders(module);
    if used.is_empty() {
        return;
    }
    // 2^53. At or above it every f64 is already an integer, so nothing needs doing — and
    // below it the i64 round-trip is exact, which is why this cannot saturate the way the
    // `as i32` workaround it replaces did.
    out.push_str(
        "const ML_INTEGRAL: f64 = 9007199254740992.0;\n\
         fn ml_trunc_raw(x: f64) -> f64 {\n\
         \x20   if x != x { return x; }\n\
         \x20   if x >= ML_INTEGRAL || x <= -ML_INTEGRAL { return x; }\n\
         \x20   (x as i64) as f64\n\
         }\n\
         // Carry x's sign onto a zero result: IEEE gives a product the XOR of the operand\n\
         // signs, so `x * 0.0` is exactly \"zero with x's sign\". Without this, ceil(-0.5)\n\
         // would be +0.0 and C would disagree (DP-R3).\n\
         fn ml_sz(r: f64, x: f64) -> f64 { if r == 0.0 { x * 0.0 } else { r } }\n",
    );
    for name in &used {
        match *name {
            "trunc" => out.push_str("fn ml_trunc(x: f64) -> f64 { ml_sz(ml_trunc_raw(x), x) }\n"),
            "floor" => out.push_str(
                "fn ml_floor(x: f64) -> f64 { let t = ml_trunc_raw(x); ml_sz(if t > x { t - 1.0 } else { t }, x) }\n",
            ),
            "ceil" => out.push_str(
                "fn ml_ceil(x: f64) -> f64 { let t = ml_trunc_raw(x); ml_sz(if t < x { t + 1.0 } else { t }, x) }\n",
            ),
            // NOT `floor(x + 0.5)`: that returns 1 for 0.49999999999999994. The fractional
            // part is computed exactly instead (`x - trunc(x)` is exact below 2^53).
            "round" => out.push_str(
                "fn ml_round(x: f64) -> f64 { let t = ml_trunc_raw(x); if t != t { return t; } let d = x - t; ml_sz(if d >= 0.5 { t + 1.0 } else if d <= -0.5 { t - 1.0 } else { t }, x) }\n",
            ),
            _ => {}
        }
    }
    out.push('\n');
}

fn op_str(op: IrBinOp) -> &'static str {
    match op {
        IrBinOp::Add => "+",
        IrBinOp::Sub => "-",
        IrBinOp::Mul => "*",
        // `Div` reaches here only for f64; the i32 form is emitted guarded above and never
        // takes this path. `Rem` is i32-only (DP-D4), so it never reaches here at all —
        // the arm exists so a future f64 `%` cannot be added without noticing this.
        IrBinOp::Div => "/",
        IrBinOp::Rem => "%",
        IrBinOp::Lt => "<",
        IrBinOp::Gt => ">",
        IrBinOp::Le => "<=",
        IrBinOp::Ge => ">=",
        IrBinOp::Eq => "==",
        IrBinOp::Ne => "!=",
        // Rust's `&&`/`||` short-circuit, which is what SPEC-logical-ops DP-B2 specifies.
        // Nothing in the language can observe that yet (no calls, no trapping operations),
        // so the SPEC records it as specified-but-unmeasured rather than claiming a test.
        IrBinOp::And => "&&",
        IrBinOp::Or => "||",
    }
}

/// Write `rust_src` as a `cdylib` crate under `workdir/<crate_name>` and build it,
/// returning the produced DLL path. Requires `cargo` on PATH (D19/D20). Windows target
/// (D22): the artifact is `<crate_name>.dll`.
///
/// This is a caller-supplied-dir primitive: the caller must pass a **unique** `workdir` per
/// concurrent invocation (`emit_artifacts` uses a private temp tree; the oracle tests
/// namespace theirs per process). Two calls sharing a `workdir` would race.
pub fn build_cdylib(
    rust_src: &str,
    crate_name: &str,
    workdir: &Path,
) -> Result<PathBuf, CodegenError> {
    let crate_dir = workdir.join(crate_name);
    std::fs::create_dir_all(crate_dir.join("src"))
        .map_err(|e| CodegenError::new(format!("create crate dir: {e}")))?;
    std::fs::write(
        crate_dir.join("Cargo.toml"),
        format!(
            "[package]\nname = \"{crate_name}\"\nversion = \"0.0.0\"\nedition = \"2021\"\npublish = false\n\n[lib]\ncrate-type = [\"cdylib\"]\n\n[profile.release]\npanic = \"abort\"\nstrip = true\nlto = true\nopt-level = \"z\"\n"
        ),
    )
    .map_err(|e| CodegenError::new(format!("write Cargo.toml: {e}")))?;
    std::fs::write(crate_dir.join("src").join("lib.rs"), rust_src)
        .map_err(|e| CodegenError::new(format!("write lib.rs: {e}")))?;

    // Capture cargo's output instead of inheriting stdio. Inheriting leaked the generated
    // crate's build chatter into the user's console: a `Compiling <name> (…\Temp\mlc-build-…)`
    // line, and any rustc diagnostic pointing at `src/lib.rs:<line>` — a file the user never
    // wrote, in a directory that is deleted right afterwards. On success there is nothing
    // worth showing; on failure the text belongs IN the error, where a caller can handle it,
    // rather than having already scrolled past.
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".into());
    let out = Command::new(cargo)
        .args(["build", "--release", "--manifest-path"])
        .arg(crate_dir.join("Cargo.toml"))
        .output()
        .map_err(|e| CodegenError::new(format!("spawn cargo: {e}")))?;
    if !out.status.success() {
        // Say whose line numbers these are. The positions are in emitted Rust, and by the
        // time anyone reads this the file is usually gone, so a bare paste would send the
        // reader looking for a `src/lib.rs` that is not theirs.
        let stderr = String::from_utf8_lossy(&out.stderr);
        return Err(CodegenError::new(format!(
            "cargo build of generated crate failed — the positions below are in the \
             GENERATED Rust, not in your source:\n{}",
            stderr.trim_end()
        )));
    }

    let dll = crate_dir
        .join("target")
        .join("release")
        .join(format!("{crate_name}.dll"));
    if !dll.exists() {
        return Err(CodegenError::new(format!(
            "expected dll not found: {}",
            dll.display()
        )));
    }
    Ok(dll)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compile_to_ir;

    #[test]
    fn emit_discount_produces_extern_c_rust() {
        let ir = compile_to_ir(include_str!("../../examples/discount.mls")).unwrap();
        let rust = emit(&ir).expect("emit");
        assert!(
            rust.contains(r#"pub extern "C" fn mlx_discount(price: f64, vip: bool) -> f64"#),
            "{rust}"
        );
        assert!(rust.contains("#![no_std]"), "{rust}");
        assert!(rust.contains("ml_module_abi_version"), "{rust}");
        assert!(rust.contains("if vip"), "{rust}");
        assert!(rust.contains("return price"), "{rust}");
    }

    #[test]
    fn rejects_function_without_guaranteed_return() {
        // Only statement is an `if` (no trailing return) → some path returns no value.
        let module = IrModule {
            errors: vec![],
            functions: vec![IrFunction {
                name: "f".into(),
                params: vec![IrParam {
                    name: "b".into(),
                    ty: IrType::Bool,
                    out: false,
                }],
                ret: IrType::F64,
                fallible: false,
                exported: true,
                body: vec![IrStmt::If {
                    cond: IrExpr {
                        ty: IrType::Bool,
                        kind: IrExprKind::Var("b".into()),
                    },
                    body: vec![IrStmt::Return(IrExpr {
                        ty: IrType::F64,
                        kind: IrExprKind::ConstF64(1.0),
                    })],
                }],
            }],
        };
        let err = emit(&module).unwrap_err();
        assert!(
            err.message.contains("return on all paths"),
            "{}",
            err.message
        );
    }
}
