//! W7 binding generators: from the typed IR, emit a C header (`.h`) and a Delphi import
//! unit (`.pas`) for a compiled module (D14 artifacts).
//!
//! Status: these bindings encode the D18 ABI (`mlx_` prefix, reserved
//! `ml_module_abi_version`, 1-byte boolean). The **C** binding is now verified end-to-end by
//! a real MSVC-built host (`hosts/c-host`, acceptance D). The **Delphi** binding is still
//! DRAFT — no `dcc64` here, so nothing has ever compiled the `.pas`.

use std::fmt::Write as _;

use crate::ir::{IrFunction, IrModule, IrType};

fn c_type(t: IrType) -> &'static str {
    match t {
        IrType::F64 => "double",
        IrType::Bool => "bool",
        IrType::I32 => "int32_t",
    }
}

fn delphi_type(t: IrType) -> &'static str {
    match t {
        IrType::F64 => "Double",
        IrType::Bool => "Boolean",
        IrType::I32 => "Integer",
    }
}

fn guard_name(dll_name: &str) -> String {
    let sanitized: String = dll_name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    format!("ML_{sanitized}_H")
}

/// Emit a C header exposing the module's exports. `dll_name` is the module name
/// (without extension), used for the include guard.
pub fn emit_c_header(module: &IrModule, dll_name: &str) -> String {
    let guard = guard_name(dll_name);
    let mut s = String::new();

    let _ = writeln!(
        s,
        "/* Generated by mlc - Mathless C ABI header for module '{dll_name}'. Do not edit."
    );
    let _ = writeln!(
        s,
        " * This GENERATOR is verified by acceptance D: a C11 host built with MSVC cl on\n \
         * Windows x64 compiles its output and calls the module through\n \
         * LoadLibrary/GetProcAddress - see hosts/c-host. That covers the generator, not this\n \
         * particular file. Not verified: other C compilers, and link-time binding via an\n \
         * import library."
    );
    let _ = writeln!(
        s,
        " * `bool` is 1 byte to match the module's extern \"C\" ABI (D18). */"
    );
    let _ = writeln!(s, "#ifndef {guard}");
    let _ = writeln!(s, "#define {guard}");
    s.push('\n');
    let _ = writeln!(s, "#include <stdint.h>");
    let _ = writeln!(s, "#include <stdbool.h>");
    s.push('\n');
    // D17 error codes (module-defined, positive i32). Constants — not exported symbols.
    if !module.errors.is_empty() {
        for e in &module.errors {
            let _ = writeln!(s, "#define ML_ERR_{} {}", e.name, e.code);
        }
        s.push('\n');
    }
    let _ = writeln!(s, "#ifdef __cplusplus");
    let _ = writeln!(s, "extern \"C\" {{");
    let _ = writeln!(s, "#endif");
    s.push('\n');

    let _ = writeln!(s, "uint32_t ml_module_abi_version(void);");
    for f in &module.functions {
        let _ = writeln!(s, "{}", c_signature(f));
    }
    s.push('\n');

    let _ = writeln!(s, "#ifdef __cplusplus");
    let _ = writeln!(s, "}}");
    let _ = writeln!(s, "#endif");
    s.push('\n');
    let _ = writeln!(s, "#endif /* {guard} */");
    s
}

fn c_signature(f: &IrFunction) -> String {
    let mut parts: Vec<String> = f
        .params
        .iter()
        .map(|p| format!("{} {}", c_type(p.ty), p.name))
        .collect();
    if f.fallible {
        // D17: i32 status return + a `T*` out-param.
        parts.push(format!("{}* out_value", c_type(f.ret)));
        format!("int32_t mlx_{}({});", f.name, join_c_params(parts))
    } else {
        format!(
            "{} mlx_{}({});",
            c_type(f.ret),
            f.name,
            join_c_params(parts)
        )
    }
}

fn join_c_params(parts: Vec<String>) -> String {
    if parts.is_empty() {
        "void".to_string()
    } else {
        parts.join(", ")
    }
}

/// Emit a Delphi import unit. `unit_name` is the Pascal unit name; `dll_name` the module
/// name (without extension) used in the `external` clause.
pub fn emit_delphi_unit(module: &IrModule, unit_name: &str, dll_name: &str) -> String {
    let mut s = String::new();

    let _ = writeln!(
        s,
        "{{ Generated by mlc - Mathless import unit for module '{dll_name}'. Do not edit."
    );
    let _ = writeln!(
        s,
        "  DRAFT: NOT yet verified against a Delphi host (D14 load gate BLOCKED)."
    );
    let _ = writeln!(
        s,
        "  Boolean is 1 byte to match the module ABI; do not use LongBool. }}"
    );
    let _ = writeln!(s, "unit {unit_name};");
    s.push('\n');
    let _ = writeln!(s, "interface");
    s.push('\n');
    let _ = writeln!(s, "const");
    let _ = writeln!(s, "  ML_MODULE = '{dll_name}.dll';");
    // D17 error codes (module-defined, positive i32).
    for e in &module.errors {
        let _ = writeln!(s, "  ML_ERR_{} = {};", e.name, e.code);
    }
    s.push('\n');
    let _ = writeln!(
        s,
        "function ml_module_abi_version: LongWord; cdecl; external ML_MODULE;"
    );
    for f in &module.functions {
        let _ = writeln!(s, "{} cdecl; external ML_MODULE;", delphi_signature(f));
    }
    s.push('\n');
    let _ = writeln!(s, "implementation");
    s.push('\n');
    let _ = writeln!(s, "end.");
    s
}

fn delphi_signature(f: &IrFunction) -> String {
    let mut parts: Vec<String> = f
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, delphi_type(p.ty)))
        .collect();
    if f.fallible {
        // D17: Integer status return + an `out` param (Delphi `out` == C `T*` for f64/bool).
        parts.push(format!("out out_value: {}", delphi_type(f.ret)));
        format!("function mlx_{}({}): Integer;", f.name, parts.join("; "))
    } else if parts.is_empty() {
        format!("function mlx_{}: {};", f.name, delphi_type(f.ret))
    } else {
        format!(
            "function mlx_{}({}): {};",
            f.name,
            parts.join("; "),
            delphi_type(f.ret)
        )
    }
}
