//! W7 binding generators: from the typed IR, emit a C header (`.h`) and a Delphi import
//! unit (`.pas`) for a compiled module (D14 artifacts).
//!
//! Status: these bindings encode the D18 ABI (`mlx_` prefix, reserved
//! `ml_module_abi_version`, 1-byte boolean). The **C** binding is now verified end-to-end by
//! a real MSVC-built host (`hosts/c-host`, acceptance D). The **Delphi** binding is still
//! DRAFT — no `dcc64` here, so nothing has ever compiled the `.pas`.

use std::fmt::Write as _;

use std::collections::HashMap;

use crate::ir::{IrFunction, IrModule, IrStmt, IrType};

fn c_type(t: IrType) -> &'static str {
    match t {
        // DP-S1: NUL-terminated, borrowed for the call.
        IrType::Str => "const char*",
        IrType::F64 => "double",
        IrType::Bool => "bool",
        IrType::I32 => "int32_t",
    }
}

fn delphi_type(t: IrType) -> &'static str {
    match t {
        // NOT Delphi's `string`: that is a UTF-16 UnicodeString, and passing one here sends
        // the wrong bytes silently (SPEC-string-input section 5.2). The unit carries a
        // warning comment for the same reason.
        IrType::Str => "PAnsiChar",
        IrType::F64 => "Double",
        IrType::Bool => "Boolean",
        IrType::I32 => "Integer",
    }
}

fn guard_name(dll_name: &str) -> String {
    let sanitized: String = dll_name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    format!("ML_{sanitized}_H")
}

/// Emit a C header exposing the module's exports. `dll_name` is the module name
/// (without extension), used for the include guard.
pub fn emit_c_header(module: &IrModule, dll_name: &str) -> String {
    let guard = guard_name(dll_name);
    let mut s = String::new();

    let _ = writeln!(
        s,
        "/* Generated by mlc - Mathless C ABI header for module '{dll_name}'. Do not edit."
    );
    let _ = writeln!(
        s,
        " * This GENERATOR is verified by acceptance D: a C11 host built with MSVC cl on\n \
         * Windows x64 compiles its output and calls the module through\n \
         * LoadLibrary/GetProcAddress - see hosts/c-host. That covers the generator, not this\n \
         * particular file. Not verified: other C compilers, and link-time binding via an\n \
         * import library."
    );
    let _ = writeln!(
        s,
        " * `bool` is 1 byte to match the module's extern \"C\" ABI (D18). */"
    );
    let _ = writeln!(s, "#ifndef {guard}");
    let _ = writeln!(s, "#define {guard}");
    s.push('\n');
    let _ = writeln!(s, "#include <stdint.h>");
    let _ = writeln!(s, "#include <stdbool.h>");
    s.push('\n');
    // DP-T6: the truncation status lives OUTSIDE the `ML_ERR_` namespace. That namespace is
    // the module's own (and Q14 already records that it is emitted without a module prefix,
    // so two modules can collide); this one is a runtime-wide band, identical in every module
    // by construction, so the `#ifndef` makes two generated headers in one translation unit
    // benign rather than a redefinition error.
    if module
        .functions
        .iter()
        .any(|f| f.exported && f.ret == IrType::Str)
    {
        let _ = writeln!(
            s,
            "/* Q12 caller-allocates protocol: a buffer too small to hold the"
        );
        let _ = writeln!(
            s,
            " * result, NUL included. Truncation is a FAILURE, not a short"
        );
        let _ = writeln!(
            s,
            " * success - nothing is written, and *ml_needed is the exact size"
        );
        let _ = writeln!(s, " * to allocate, in the same unit as ml_cap. */");
        let _ = writeln!(s, "#ifndef ML_ST_INSUFFICIENT_BUFFER");
        let _ = writeln!(s, "#define ML_ST_INSUFFICIENT_BUFFER (-1)");
        let _ = writeln!(s, "#endif");
        s.push('\n');
    }
    // D17 error codes (module-defined, positive i32). Constants — not exported symbols.
    if !module.errors.is_empty() {
        for e in &module.errors {
            let _ = writeln!(s, "#define ML_ERR_{} {}", e.name, e.code);
        }
        s.push('\n');
    }
    let _ = writeln!(s, "#ifdef __cplusplus");
    let _ = writeln!(s, "extern \"C\" {{");
    let _ = writeln!(s, "#endif");
    s.push('\n');

    let _ = writeln!(s, "uint32_t ml_module_abi_version(void);");
    let provenance = error_provenance(module);
    // Bindings describe the module's SURFACE: internal functions are not callable by a host
    // and must not appear here (SPEC-calls section 2.3).
    for f in module.functions.iter().filter(|f| f.exported) {
        // DP-F10: which codes can actually reach the host through THIS function. Comments
        // only — the declaration below is byte-identical to what it was before.
        if f.fallible {
            if let Some(codes) = provenance.get(f.name.as_str()) {
                let list = if codes.is_empty() {
                    "(no domain error)".to_string()
                } else {
                    codes
                        .iter()
                        .map(|c| format!("ML_ERR_{c}"))
                        .collect::<Vec<_>>()
                        .join(", ")
                };
                let _ = writeln!(s, "/* may fail with: {list} */");
            }
        }
        let _ = writeln!(s, "{}", c_signature(f));
    }
    s.push('\n');

    let _ = writeln!(s, "#ifdef __cplusplus");
    let _ = writeln!(s, "}}");
    let _ = writeln!(s, "#endif");
    s.push('\n');
    let _ = writeln!(s, "#endif /* {guard} */");
    s
}

/// For every function, the error NAMES it can fail with — its own `fail`s plus everything
/// reachable through `try` (DP-F10).
///
/// Only `try` edges carry errors: a plain call cannot target a fallible callee, so an
/// infallible helper can never contribute a code. `reject_recursion` has already proved the
/// call graph acyclic, so the walk terminates without a visited-set for cycles — but one is
/// kept anyway, because this function must not hang if it is ever reached with hand-built IR.
///
/// Names, not numbers: the header prints `ML_ERR_<NAME>`, which is what a host reads.
fn error_provenance(module: &IrModule) -> HashMap<&str, Vec<String>> {
    let code_name: HashMap<i32, &str> = module
        .errors
        .iter()
        .map(|e| (e.code, e.name.as_str()))
        .collect();

    /// Direct `fail` codes and `try` callees of one body.
    fn scan<'a>(body: &'a [IrStmt], codes: &mut Vec<i32>, callees: &mut Vec<&'a str>) {
        for s in body {
            match s {
                IrStmt::Fail(c) => codes.push(*c),
                IrStmt::TryCall { callee, .. } => callees.push(callee.as_str()),
                IrStmt::If { body, .. } | IrStmt::While { body, .. } => scan(body, codes, callees),
                IrStmt::Return(_)
                | IrStmt::Let { .. }
                | IrStmt::Assign { .. }
                | IrStmt::AssignOut { .. } => {}
            }
        }
    }

    let mut direct: HashMap<&str, (Vec<i32>, Vec<&str>)> = HashMap::new();
    for f in &module.functions {
        let (mut codes, mut callees) = (Vec::new(), Vec::new());
        scan(&f.body, &mut codes, &mut callees);
        direct.insert(f.name.as_str(), (codes, callees));
    }

    fn reach<'a>(
        name: &'a str,
        direct: &HashMap<&'a str, (Vec<i32>, Vec<&'a str>)>,
        seen: &mut Vec<&'a str>,
        out: &mut Vec<i32>,
    ) {
        if seen.contains(&name) {
            return;
        }
        seen.push(name);
        let Some((codes, callees)) = direct.get(name) else {
            return;
        };
        for c in codes {
            if !out.contains(c) {
                out.push(*c);
            }
        }
        for callee in callees {
            reach(callee, direct, seen, out);
        }
    }

    let mut result = HashMap::new();
    for f in &module.functions {
        let mut codes = Vec::new();
        let mut seen = Vec::new();
        reach(f.name.as_str(), &direct, &mut seen, &mut codes);
        codes.sort_unstable();
        result.insert(
            f.name.as_str(),
            codes
                .iter()
                .filter_map(|c| code_name.get(c).map(|n| (*n).to_string()))
                .collect(),
        );
    }
    result
}

fn c_signature(f: &IrFunction) -> String {
    let mut parts: Vec<String> = f
        .params
        .iter()
        .map(|p| {
            // A declared `out` is a pointer, exactly like D17's `out_value` below it.
            if p.out {
                format!("{}* {}", c_type(p.ty), p.name)
            } else {
                format!("{} {}", c_type(p.ty), p.name)
            }
        })
        .collect();
    if f.ret == IrType::Str {
        // SPEC-string-return DP-T1/T4: the Q12 triple IS the return value, so it comes last
        // (DP-O1 unchanged). `ml_cap` and `*ml_needed` are total bytes INCLUDING the NUL, on
        // every path — so the host's retry is exactly `ml_cap = *ml_needed`.
        parts.push("char* ml_buf".to_string());
        parts.push("int32_t ml_cap".to_string());
        parts.push("int32_t* ml_needed".to_string());
        format!("int32_t mlx_{}({});", f.name, join_c_params(parts))
    } else if f.fallible {
        // D17: i32 status return + a `T*` out-param.
        parts.push(format!("{}* out_value", c_type(f.ret)));
        format!("int32_t mlx_{}({});", f.name, join_c_params(parts))
    } else {
        format!(
            "{} mlx_{}({});",
            c_type(f.ret),
            f.name,
            join_c_params(parts)
        )
    }
}

fn join_c_params(parts: Vec<String>) -> String {
    if parts.is_empty() {
        "void".to_string()
    } else {
        parts.join(", ")
    }
}

/// Emit a Delphi import unit. `unit_name` is the Pascal unit name; `dll_name` the module
/// name (without extension) used in the `external` clause.
pub fn emit_delphi_unit(module: &IrModule, unit_name: &str, dll_name: &str) -> String {
    let mut s = String::new();

    let _ = writeln!(
        s,
        "{{ Generated by mlc - Mathless import unit for module '{dll_name}'. Do not edit."
    );
    let _ = writeln!(
        s,
        "  DRAFT: NOT yet verified against a Delphi host (D14 load gate BLOCKED)."
    );
    let _ = writeln!(
        s,
        "  Boolean is 1 byte to match the module ABI; do not use LongBool."
    );
    // Only when the module actually takes a string — an unrelated module should not carry a
    // warning about a type it never mentions.
    if module
        .functions
        .iter()
        .any(|f| f.exported && f.params.iter().any(|p| p.ty == IrType::Str))
    {
        // Deliberately spells out which cast does what: the blanket "a UnicodeString silently
        // matches nothing" is only true of the Pointer() spelling. Nothing here is measured -
        // there is no dcc64 on the machine that generates it - so it says so.
        let _ = writeln!(
            s,
            "\n  PAnsiChar is NOT Delphi's `string`, which is UTF-16 (UnicodeString). The module\n  \
             compares BYTES up to the NUL and never inspects the encoding (SPEC-string-input\n  \
             DP-S2), so how you build the argument decides whether it can match at all:\n  \
             - PAnsiChar(AnsiString(S)) - correct. Keep the AnsiString in a local for the\n    \
             duration of the call; the temporary in a cast expression lives only for the\n    \
             statement.\n  \
             - PAnsiChar(S) on a UnicodeString - compiles with an implicit-cast warning and\n    \
             converts through the ANSI code page. ASCII survives; anything else may not.\n  \
             - PAnsiChar(Pointer(S)) - WRONG and silent. It reinterprets UTF-16 bytes, so the\n    \
             comparison matches nothing and nothing crashes.\n  \
             UNVERIFIED (E1): no Delphi compiler has ever built this unit - see the DRAFT note\n  \
             above. This paragraph is from Embarcadero's documented behaviour, not a measurement."
        );
    }
    let _ = writeln!(s, "  }}");
    let _ = writeln!(s, "unit {unit_name};");
    s.push('\n');
    let _ = writeln!(s, "interface");
    s.push('\n');
    let _ = writeln!(s, "const");
    let _ = writeln!(s, "  ML_MODULE = '{dll_name}.dll';");
    // D17 error codes (module-defined, positive i32).
    for e in &module.errors {
        let _ = writeln!(s, "  ML_ERR_{} = {};", e.name, e.code);
    }
    s.push('\n');
    let _ = writeln!(
        s,
        "function ml_module_abi_version: LongWord; cdecl; external ML_MODULE;"
    );
    for f in module.functions.iter().filter(|f| f.exported) {
        let _ = writeln!(s, "{} cdecl; external ML_MODULE;", delphi_signature(f));
    }
    s.push('\n');
    let _ = writeln!(s, "implementation");
    s.push('\n');
    let _ = writeln!(s, "end.");
    s
}

fn delphi_signature(f: &IrFunction) -> String {
    let mut parts: Vec<String> = f
        .params
        .iter()
        .map(|p| {
            // Delphi already spells this for `out_value`; a declared out gets the same keyword.
            if p.out {
                format!("out {}: {}", p.name, delphi_type(p.ty))
            } else {
                format!("{}: {}", p.name, delphi_type(p.ty))
            }
        })
        .collect();
    if f.ret == IrType::Str {
        // DP-T3: `PByte`, deliberately NOT `PAnsiChar`. Both silent Delphi misspellings that
        // the string-INPUT slice could only warn about — `PAnsiChar(S)` on a UnicodeString and
        // `PAnsiChar(Pointer(S))` — become COMPILE ERRORS against a `PByte` parameter. Loud
        // beats documented.
        //
        // `ml_buf` is a VALUE parameter, never `out ml_buf: PByte`: that spelling passes a
        // `PByte*`, and the module would write the answer's first bytes over the host's
        // pointer variable instead of into the buffer.
        parts.push("ml_buf: PByte".to_string());
        parts.push("ml_cap: Integer".to_string());
        parts.push("out ml_needed: Integer".to_string());
        format!("function mlx_{}({}): Integer;", f.name, parts.join("; "))
    } else if f.fallible {
        // D17: Integer status return + an `out` param (Delphi `out` == C `T*` for f64/bool).
        parts.push(format!("out out_value: {}", delphi_type(f.ret)));
        format!("function mlx_{}({}): Integer;", f.name, parts.join("; "))
    } else if parts.is_empty() {
        format!("function mlx_{}: {};", f.name, delphi_type(f.ret))
    } else {
        format!(
            "function mlx_{}({}): {};",
            f.name,
            parts.join("; "),
            delphi_type(f.ret)
        )
    }
}
