//! Golden snapshots of everything `mlc` emits from source, over EVERY example.
//!
//! WW1a of SPEC-export-wrappers. The wrapper refactor rewrites how every export is emitted,
//! and an adversarial pass measured what the planned checks would and would not see:
//!
//! - The `.h` and `.pas` cannot move under a backend-only change: `header.rs` takes
//!   `(&IrModule, name)` and never sees `codegen.rs`. They are still worth freezing — they
//!   catch the frontend work (WW3/WW4) and they catch a backend change that accidentally
//!   perturbs the IR — but they are a FRONTEND invariant, not proof the backend is intact.
//! - The generated **Rust** is the only artifact the refactor actually changes, and nothing
//!   snapshotted it. That made "the widest change in the repo" unreviewable.
//!
//! So this file freezes all three, for all examples, in one golden file each. The Rust golden
//! is not an invariant — the refactor is supposed to change it — it is a way to turn a diffuse
//! change into **one diff, reviewed once**.
//!
//! Regenerate deliberately with `MATHLESS_BLESS=1 cargo test -p mlc --test golden`, and read
//! the diff before committing it. That is the whole point: blessing is easy, but it shows you
//! exactly what moved.

use std::path::{Path, PathBuf};

use mlc::{compile_to_ir, compile_to_rust};

fn examples_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("examples")
}

/// Every `examples/*.mls`, sorted, so the golden file has a stable order.
fn examples() -> Vec<(String, String)> {
    let mut out: Vec<(String, String)> = std::fs::read_dir(examples_dir())
        .expect("read examples/")
        .filter_map(|e| {
            let p = e.ok()?.path();
            if p.extension()? != "mls" {
                return None;
            }
            let name = p.file_stem()?.to_str()?.to_string();
            Some((name, std::fs::read_to_string(&p).ok()?))
        })
        .collect();
    out.sort_by(|a, b| a.0.cmp(&b.0));
    assert!(
        out.len() >= 16,
        "expected the whole corpus, got {}",
        out.len()
    );
    out
}

/// Compare `actual` against `tests/golden/<file>`, or rewrite it under `MATHLESS_BLESS=1`.
fn check_golden(file: &str, actual: &str) {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("golden")
        .join(file);
    // Normalise line endings: the repo is checked out with CRLF on Windows, and a golden file
    // that disagrees with itself across platforms is worse than no golden file.
    let actual = actual.replace("\r\n", "\n");
    if std::env::var("MATHLESS_BLESS").is_ok() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &actual).unwrap();
        return;
    }
    let expected = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| {
            panic!(
                "missing golden {}: {e}\nrun with MATHLESS_BLESS=1",
                path.display()
            )
        })
        .replace("\r\n", "\n");
    if expected != actual {
        // Report the first differing line rather than dumping two whole files.
        let (a, b): (Vec<&str>, Vec<&str>) = (expected.lines().collect(), actual.lines().collect());
        let at = a.iter().zip(b.iter()).position(|(x, y)| x != y);
        let detail = match at {
            Some(i) => format!(
                "first difference at line {}:\n  golden: {}\n  actual: {}",
                i + 1,
                a[i],
                b[i]
            ),
            None => format!(
                "lengths differ: golden {} lines, actual {}",
                a.len(),
                b.len()
            ),
        };
        panic!(
            "{} is out of date.\n{detail}\n\nIf the change is intended, re-bless it and READ the \
             diff:\n  MATHLESS_BLESS=1 cargo test -p mlc --test golden",
            path.display()
        );
    }
}

fn banner(name: &str) -> String {
    format!("\n{}\n=== {name} ===\n{}\n", "=".repeat(60), "=".repeat(60))
}

#[test]
fn the_generated_rust_is_frozen() {
    // The artifact the refactor changes. Deliberately one file for the whole corpus: the
    // wrapper refactor touches every export, and a single diff is what makes that reviewable.
    let mut all = String::from(
        "// GOLDEN — generated by `cargo test -p mlc --test golden`. Do not hand-edit.\n\
         // This is the Rust `mlc` emits for every examples/*.mls. It is NOT an invariant:\n\
         // a backend change is supposed to move it. It exists so that a change to the\n\
         // emission path is one reviewable diff instead of a diffuse rewrite.\n",
    );
    for (name, src) in examples() {
        all.push_str(&banner(&name));
        all.push_str(&compile_to_rust(&src).unwrap_or_else(|e| panic!("{name}: {e}")));
    }
    check_golden("generated.rs.txt", &all);
}

#[test]
fn the_c_headers_are_frozen() {
    // A FRONTEND invariant (see the module comment): `header.rs` never sees `codegen.rs`.
    let mut all = String::from("// GOLDEN — the C header for every examples/*.mls.\n");
    for (name, src) in examples() {
        let ir = compile_to_ir(&src).unwrap_or_else(|e| panic!("{name}: {e}"));
        all.push_str(&banner(&name));
        all.push_str(&mlc::header::emit_c_header(&ir, &name));
    }
    check_golden("headers.h.txt", &all);
}

#[test]
fn the_delphi_units_are_frozen() {
    // Nothing covered the `.pas` corpus-wide before this. It is the binding for D14's
    // flagship host and no compiler has ever read it, so freezing the text is the only
    // regression signal available at all.
    let mut all = String::from("// GOLDEN — the Delphi import unit for every examples/*.mls.\n");
    for (name, src) in examples() {
        let ir = compile_to_ir(&src).unwrap_or_else(|e| panic!("{name}: {e}"));
        let unit = format!("Mlx_{}", name);
        all.push_str(&banner(&name));
        all.push_str(&mlc::header::emit_delphi_unit(&ir, &unit, &name));
    }
    check_golden("units.pas.txt", &all);
}

#[test]
fn every_exported_example_function_is_called_by_an_oracle_test() {
    // The snapshots above observe no VALUES. A wrong adapter reproduces every one of them
    // exactly — measured: a swapped-argument adapter matched the header, the Delphi unit, the
    // export set, the import set and the file size, differing only in `.text` bytes.
    //
    // So the real safety net is the oracle suite, and today its coverage of the corpus is
    // ACCIDENTAL — every `export fn` happens to be called by some test, and nothing says it
    // must stay that way. This is that "nothing", made cheap: no build, no load, just a grep.
    let tests = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("hosts")
        .join("rust-oracle")
        .join("tests");
    let corpus: String = std::fs::read_dir(&tests)
        .expect("read oracle tests")
        .filter_map(|e| std::fs::read_to_string(e.ok()?.path()).ok())
        .collect();

    let mut missing = Vec::new();
    for (name, src) in examples() {
        for line in src.lines() {
            let line = line.trim();
            let Some(rest) = line.strip_prefix("export fn ") else {
                continue;
            };
            let fname: String = rest
                .chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_')
                .collect();
            if fname.is_empty() {
                continue;
            }
            // The SYMBOL-LOOKUP form, not a bare substring. `corpus.contains("mlx_{fname}")`
            // was satisfied by two things that are not a call (STATUS §9-A A12):
            //
            //   - a mention in a comment — there are ten such lines in the oracle corpus, and
            //     `int32_t mlx_safe_div(double, double, double*)` written above a test as
            //     documentation covered `safe_div` whether or not anything called it;
            //   - a PREFIX collision — `mlx_discount` is a prefix of `mlx_discount4`, so a
            //     test that only ever loaded `discount4` also "covered" `discount`.
            //
            // Every one of the 41 exported example functions is resolved as `b"mlx_<n>\0"`
            // today (measured), and the trailing NUL closes both holes at once: it cannot
            // appear in prose, and it cannot be a prefix of another name.
            let needle = format!("b\"mlx_{fname}\\0\"");
            if !corpus.contains(&needle) {
                missing.push(format!("{name}.mls::{fname}"));
            }
        }
    }
    assert!(
        missing.is_empty(),
        "these exported example functions are never called by an oracle test, so a wrong \
         adapter for their shape would ship silently:\n  {}\n\nAdd a test that loads the \
         module and calls them, or drop the example. (Recognised by the symbol lookup \
         `m.symbol(b\"mlx_<name>\\0\")`. A name composed at run time is deliberately not \
         recognised: the point is that a named call site exists.)",
        missing.join("\n  ")
    );
}

#[test]
fn the_corpus_still_contains_an_error_name_collision() {
    // `examples/refund.mls` exists to BE a collision: it declares an error name that another
    // example also declares, with a different value. Acceptance D includes every example's
    // header in one translation unit, so before the module prefix (Q14) that corpus failed to
    // build with `C4005: macro redefinition` under `/WX` — measured, 41 s.
    //
    // The fixture was added; nothing pinned the property that makes it one (STATUS §9-A A13).
    // Rename the name in either file and the corpus quietly stops exercising the prefix, while
    // every test — including acceptance D — stays green, because a corpus with no collision
    // cannot collide.
    //
    // Deliberately NOT hardcoding `E_NEG`, `refund` or `shapes`: what must hold is the
    // property, so a future rename that keeps a collision is fine and one that removes it is
    // not.
    let mut by_name: std::collections::BTreeMap<String, Vec<(String, String)>> =
        std::collections::BTreeMap::new();
    for (module, src) in examples() {
        for line in src.lines() {
            let Some(rest) = line.trim().strip_prefix("error ") else {
                continue;
            };
            let Some((name, value)) = rest.split_once('=') else {
                continue;
            };
            by_name
                .entry(name.trim().to_string())
                .or_default()
                .push((module.clone(), value.trim().to_string()));
        }
    }

    let collisions: Vec<_> = by_name
        .iter()
        .filter(|(_, uses)| uses.len() > 1 && uses.iter().any(|(_, v)| *v != uses[0].1))
        .collect();
    assert!(
        !collisions.is_empty(),
        "no two examples declare the same error name with different values any more, so the \
         corpus no longer exercises the module prefix that SPEC-error-prefix added — and \
         acceptance D would stay green with the prefix removed. Declarations found: {by_name:?}"
    );
    println!("error-name collisions kept as fixtures: {collisions:?}");
}
